[package]
name = "consistency"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
rss-request-context.workspace = true
vocab = { path = "../vocab" }
thiserror = { workspace = true }
uuid = { workspace = true, features = ["v4"] }
serde_json = { workspace = true, features = ["arbitrary_precision"] }
sha2 = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
trybuild = { workspace = true }
