[package]
name = "rss"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[lints]
workspace = true

[[bin]]
name = "rss"
path = "src/main.rs"

[dependencies]
runtime = { path = "../../assemblies/runtime", features = ["operator-cli"] }
postgres-migration = { path = "../../adapters/postgres-migration" }
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
anyhow = { workspace = true }
tracing-subscriber = { workspace = true }
