[package]
name = "postgres"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
consistency = { path = "../../crates/consistency" }
diport = { path = "../../crates/diport" }
rss-runtime.workspace = true
futures = { workspace = true }
rss-request-context.workspace = true
rustls.workspace = true
rustls-pki-types.workspace = true
sqlx = { workspace = true }
thiserror = { workspace = true }
zeroize.workspace = true

[features]
default = []
test-support = []

[dev-dependencies]
rcgen = { workspace = true }
static_assertions = { workspace = true }
