[package]
name = "distributed"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
vocab = { path = "../vocab" }
ids = { path = "../ids" }
secure = { path = "../secure" }
support = { path = "../support" }
runctx = { path = "../runctx" }
consistency = { path = "../consistency" }
primitives = { path = "../primitives" }
thiserror = { workspace = true }
diport = { path = "../diport" }
futures = { workspace = true }
metrics = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true, features = ["macros", "sync", "time"] }

[dev-dependencies]
metrics-exporter-prometheus = { workspace = true }
tokio = { workspace = true, features = ["rt", "rt-multi-thread"] }
