[package]
name = "distributed"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
rss-transactional-messaging.workspace = true
rss-request-context.workspace = true
vocab = { path = "../vocab" }
ids = { path = "../ids" }
rss-redact = { workspace = true, features = ["derive"] }
support = { path = "../support" }
runctx = { path = "../runctx" }
consistency = { path = "../consistency" }
primitives = { path = "../primitives" }
thiserror = { workspace = true }
diport = { path = "../diport" }
futures = { workspace = true, features = ["std", "async-await", "executor"] }
metrics = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_json_canonicalizer = { workspace = true }
sha2 = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true, features = ["macros", "sync", "time", "rt-multi-thread"] }
url = { workspace = true }

[dev-dependencies]
metrics-exporter-prometheus = { workspace = true }
testkit = { path = "../testkit" }
tokio = { workspace = true, features = ["rt", "rt-multi-thread", "macros"] }
