[package]
name = "listenerlifecycle"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
diport = { path = "../diport" }
rss-runtime.workspace = true
tokio = { workspace = true, features = ["net", "rt-multi-thread", "macros"] }
tokio-util = { workspace = true }

