[package]
name = "eventexec"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
futures = { workspace = true }
thiserror = { workspace = true }
tokio-util = { workspace = true }
uuid = { workspace = true, features = ["v4"] }
