// @generated by cargo xtask codegen from contracts/http/runtime/v1/inventory; do not edit.

use std::error::Error;
use std::fmt;

use crate::{ContractId, ContractVersion, SchemaDigest};

pub enum RuntimeInventory {}

impl crate::runtime::private::Sealed for RuntimeInventory {}
impl crate::Contract for RuntimeInventory {
    type Request = RuntimeInventoryRequest;
    type Response = RuntimeInventoryResponse;
    const ID: ContractId = ContractId::from_static("runtime.inventory");
    const VERSION: ContractVersion = ContractVersion::new(1, 0);
    const SCHEMA_DIGEST: SchemaDigest = SchemaDigest::from_static(
        "sha256:95cff700e1fca1f72a566f493ae738be1e5a4c52c8d5383825fb7d4c7f56998b",
    );
    const PERMISSION: &'static str = "runtime:inventory:read";
}

#[derive(Clone, Default)]
pub struct RuntimeInventoryRequest;

pub struct RuntimeInventoryResponse {
    data: RuntimeInventoryData,
}
impl RuntimeInventoryResponse {
    pub fn new(data: RuntimeInventoryData) -> Self {
        Self { data }
    }
    pub fn data(&self) -> &RuntimeInventoryData {
        &self.data
    }
    pub fn into_data(self) -> RuntimeInventoryData {
        self.data
    }
}

pub struct RuntimeInventoryData {
    assembly_fingerprint: Sha256Fingerprint,
    build_metadata: Option<RuntimeBuildMetadata>,
    runtime_plan_fingerprint: Sha256Fingerprint,
    activated_workflows: Vec<RuntimeActivatedWorkflow>,
    domains: Vec<RuntimeDomain>,
    listeners: Vec<RuntimeListener>,
    provider_posture: Vec<RuntimeProviderPosture>,
    placements: Vec<RuntimePlacement>,
}

impl RuntimeInventoryData {
    pub fn new(
        assembly_fingerprint: Sha256Fingerprint,
        runtime_plan_fingerprint: Sha256Fingerprint,
        domains: Vec<RuntimeDomain>,
    ) -> Result<Self, InventoryValueError> {
        if domains.is_empty() {
            return Err(InventoryValueError::new(
                InventoryValueErrorCode::DomainsEmpty,
            ));
        }
        if has_duplicates(&domains, |left, right| left == right) {
            return Err(InventoryValueError::new(
                InventoryValueErrorCode::DomainsDuplicate,
            ));
        }
        Ok(Self {
            assembly_fingerprint,
            build_metadata: None,
            runtime_plan_fingerprint,
            activated_workflows: Vec::new(),
            domains,
            listeners: Vec::new(),
            provider_posture: Vec::new(),
            placements: Vec::new(),
        })
    }
    pub const fn schema_version(&self) -> u16 {
        1
    }
    pub fn assembly_fingerprint(&self) -> &Sha256Fingerprint {
        &self.assembly_fingerprint
    }
    pub fn runtime_plan_fingerprint(&self) -> &Sha256Fingerprint {
        &self.runtime_plan_fingerprint
    }
    pub fn build_metadata(&self) -> Option<&RuntimeBuildMetadata> {
        self.build_metadata.as_ref()
    }
    pub fn activated_workflows(&self) -> &[RuntimeActivatedWorkflow] {
        &self.activated_workflows
    }
    pub fn domains(&self) -> &[RuntimeDomain] {
        &self.domains
    }
    pub fn listeners(&self) -> &[RuntimeListener] {
        &self.listeners
    }
    pub fn provider_posture(&self) -> &[RuntimeProviderPosture] {
        &self.provider_posture
    }
    pub fn placements(&self) -> &[RuntimePlacement] {
        &self.placements
    }
    pub fn with_build_metadata(mut self, value: RuntimeBuildMetadata) -> Self {
        self.build_metadata = Some(value);
        self
    }
    pub fn with_activated_workflows(
        mut self,
        value: Vec<RuntimeActivatedWorkflow>,
    ) -> Result<Self, InventoryValueError> {
        if has_duplicates(&value, |left, right| left.identity() == right.identity()) {
            return Err(InventoryValueError::new(
                InventoryValueErrorCode::WorkflowsDuplicate,
            ));
        }
        self.activated_workflows = value;
        Ok(self)
    }
    pub fn with_listeners(
        mut self,
        value: Vec<RuntimeListener>,
    ) -> Result<Self, InventoryValueError> {
        if !strictly_ordered_by(&value, |listener| listener.id()) {
            return Err(InventoryValueError::new(
                InventoryValueErrorCode::ListenersNotCanonical,
            ));
        }
        self.listeners = value;
        Ok(self)
    }
    pub fn with_provider_posture(
        mut self,
        value: Vec<RuntimeProviderPosture>,
    ) -> Result<Self, InventoryValueError> {
        if !strictly_ordered_by(&value, |provider| provider.id()) {
            return Err(InventoryValueError::new(
                InventoryValueErrorCode::ProvidersNotCanonical,
            ));
        }
        self.provider_posture = value;
        Ok(self)
    }
    pub fn with_placements(
        mut self,
        value: Vec<RuntimePlacement>,
    ) -> Result<Self, InventoryValueError> {
        if value
            .windows(2)
            .any(|pair| pair[0].canonical_key() >= pair[1].canonical_key())
        {
            return Err(InventoryValueError::new(
                InventoryValueErrorCode::PlacementsNotCanonical,
            ));
        }
        self.placements = value;
        Ok(self)
    }
}

#[derive(Clone, Eq, PartialEq)]
pub struct Sha256Fingerprint(Box<str>);
impl Sha256Fingerprint {
    pub fn parse(value: &str) -> Result<Self, InventoryValueError> {
        if value.len() != 71
            || !value.starts_with("sha256:")
            || !value[7..]
                .bytes()
                .all(|byte| byte.is_ascii_digit() || (b'a'..=b'f').contains(&byte))
        {
            return Err(InventoryValueError::new(
                InventoryValueErrorCode::Fingerprint,
            ));
        }
        Ok(Self(value.into()))
    }
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

pub struct RuntimeBuildMetadata {
    source_revision: Box<str>,
    image_digest: Sha256Fingerprint,
}
impl RuntimeBuildMetadata {
    pub fn new(
        source_revision: &str,
        image_digest: Sha256Fingerprint,
    ) -> Result<Self, InventoryValueError> {
        if !matches!(source_revision.len(), 40 | 64)
            || !source_revision
                .bytes()
                .all(|byte| byte.is_ascii_hexdigit() && !byte.is_ascii_uppercase())
        {
            return Err(InventoryValueError::new(
                InventoryValueErrorCode::SourceRevision,
            ));
        }
        Ok(Self {
            source_revision: source_revision.into(),
            image_digest,
        })
    }
    pub fn source_revision(&self) -> &str {
        &self.source_revision
    }
    pub fn image_digest(&self) -> &Sha256Fingerprint {
        &self.image_digest
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum RuntimeDomain {
    Identity,
    Settings,
    Audit,
    ContractRegistry,
    SystemHealth,
}

pub struct RuntimeListener {
    id: Box<str>,
    kind: RuntimeListenerKind,
    endpoint: RuntimeListenerEndpoint,
    auth_scheme: RuntimeAuthScheme,
}
impl RuntimeListener {
    pub fn new(
        id: &str,
        kind: RuntimeListenerKind,
        endpoint: RuntimeListenerEndpoint,
        auth_scheme: RuntimeAuthScheme,
    ) -> Result<Self, InventoryValueError> {
        if id.is_empty() {
            return Err(InventoryValueError::new(
                InventoryValueErrorCode::Identifier,
            ));
        }
        Ok(Self {
            id: id.into(),
            kind,
            endpoint,
            auth_scheme,
        })
    }
    pub fn id(&self) -> &str {
        &self.id
    }
    pub const fn kind(&self) -> RuntimeListenerKind {
        self.kind
    }
    pub fn endpoint(&self) -> &RuntimeListenerEndpoint {
        &self.endpoint
    }
    pub const fn auth_scheme(&self) -> RuntimeAuthScheme {
        self.auth_scheme
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum RuntimeListenerKind {
    Primary,
    Internal,
    Health,
    Admin,
}
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum RuntimeAuthScheme {
    NoAuth,
    RssAccessToken,
    FederatedAccessToken,
    MutualTls,
    ServiceToken,
}

pub struct RuntimeListenerEndpoint {
    scheme: RuntimeEndpointScheme,
    host: Box<str>,
    port: u16,
}
impl RuntimeListenerEndpoint {
    pub fn new(
        scheme: RuntimeEndpointScheme,
        host: &str,
        port: u16,
    ) -> Result<Self, InventoryValueError> {
        if host.is_empty() || host.len() > 253 || port == 0 {
            return Err(InventoryValueError::new(InventoryValueErrorCode::Endpoint));
        }
        Ok(Self {
            scheme,
            host: host.into(),
            port,
        })
    }
    pub const fn scheme(&self) -> RuntimeEndpointScheme {
        self.scheme
    }
    pub fn host(&self) -> &str {
        &self.host
    }
    pub const fn port(&self) -> u16 {
        self.port
    }
}
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum RuntimeEndpointScheme {
    Http,
    Https,
}

pub struct RuntimeProviderPosture {
    id: Box<str>,
    state: RuntimeProviderState,
}
impl RuntimeProviderPosture {
    pub fn new(id: &str, state: RuntimeProviderState) -> Result<Self, InventoryValueError> {
        if id.is_empty() {
            return Err(InventoryValueError::new(
                InventoryValueErrorCode::Identifier,
            ));
        }
        Ok(Self {
            id: id.into(),
            state,
        })
    }
    pub fn id(&self) -> &str {
        &self.id
    }
    pub const fn state(&self) -> RuntimeProviderState {
        self.state
    }
}
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum RuntimeProviderState {
    Unobserved,
    Ready,
    Degraded,
    Unavailable,
}

pub enum RuntimeActivatedWorkflow {
    Projection(RuntimeActivatedProjection),
    Saga(RuntimeActivatedSaga),
}
impl RuntimeActivatedWorkflow {
    fn identity(&self) -> (u8, &str) {
        match self {
            Self::Projection(value) => (0, value.id()),
            Self::Saga(value) => (1, value.id()),
        }
    }
}
pub struct RuntimeActivatedProjection {
    id: Box<str>,
    definition_version: Box<str>,
    schema_digest: Sha256Fingerprint,
    activation: RuntimeProjectionActivation,
}
pub struct RuntimeActivatedSaga {
    id: Box<str>,
    definition_version: Box<str>,
    schema_digest: Sha256Fingerprint,
}
impl RuntimeActivatedProjection {
    pub fn new(
        id: &str,
        definition_version: &str,
        schema_digest: Sha256Fingerprint,
        activation: RuntimeProjectionActivation,
    ) -> Result<Self, InventoryValueError> {
        validate_workflow(id, definition_version)?;
        Ok(Self {
            id: id.into(),
            definition_version: definition_version.into(),
            schema_digest,
            activation,
        })
    }
    pub fn id(&self) -> &str {
        &self.id
    }
    pub fn definition_version(&self) -> &str {
        &self.definition_version
    }
    pub fn schema_digest(&self) -> &Sha256Fingerprint {
        &self.schema_digest
    }
    pub const fn activation(&self) -> RuntimeProjectionActivation {
        self.activation
    }
}
impl RuntimeActivatedSaga {
    pub fn new(
        id: &str,
        definition_version: &str,
        schema_digest: Sha256Fingerprint,
    ) -> Result<Self, InventoryValueError> {
        validate_workflow(id, definition_version)?;
        Ok(Self {
            id: id.into(),
            definition_version: definition_version.into(),
            schema_digest,
        })
    }
    pub fn id(&self) -> &str {
        &self.id
    }
    pub fn definition_version(&self) -> &str {
        &self.definition_version
    }
    pub fn schema_digest(&self) -> &Sha256Fingerprint {
        &self.schema_digest
    }
}
fn validate_workflow(id: &str, version: &str) -> Result<(), InventoryValueError> {
    if id.is_empty()
        || !version.starts_with('v')
        || version.len() < 2
        || !version[1..].bytes().all(|byte| byte.is_ascii_digit())
    {
        return Err(InventoryValueError::new(InventoryValueErrorCode::Workflow));
    }
    Ok(())
}
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum RuntimeProjectionActivation {
    CaptureOnly,
    Shadow,
    Active,
}

pub struct RuntimePlacement {
    domain: RuntimeDomain,
    workload: Box<str>,
    mode: RuntimePlacementMode,
    endpoint: Option<RuntimeListenerEndpoint>,
    spiffe_identity: Option<Box<str>>,
    readiness: RuntimePlacementReadiness,
}
impl RuntimePlacement {
    pub fn new(
        domain: RuntimeDomain,
        workload: &str,
        mode: RuntimePlacementMode,
        readiness: RuntimePlacementReadiness,
    ) -> Result<Self, InventoryValueError> {
        if workload.is_empty() {
            return Err(InventoryValueError::new(
                InventoryValueErrorCode::Identifier,
            ));
        }
        Ok(Self {
            domain,
            workload: workload.into(),
            mode,
            endpoint: None,
            spiffe_identity: None,
            readiness,
        })
    }
    pub const fn domain(&self) -> RuntimeDomain {
        self.domain
    }
    pub fn workload(&self) -> &str {
        &self.workload
    }
    pub const fn mode(&self) -> RuntimePlacementMode {
        self.mode
    }
    pub fn endpoint(&self) -> Option<&RuntimeListenerEndpoint> {
        self.endpoint.as_ref()
    }
    pub fn spiffe_identity(&self) -> Option<&str> {
        self.spiffe_identity.as_deref()
    }
    pub const fn readiness(&self) -> RuntimePlacementReadiness {
        self.readiness
    }
    fn canonical_key(&self) -> (u8, &str) {
        (self.domain.canonical_rank(), self.workload())
    }
    pub fn with_endpoint(mut self, endpoint: RuntimeListenerEndpoint) -> Self {
        self.endpoint = Some(endpoint);
        self
    }
    pub fn with_spiffe_identity(mut self, identity: &str) -> Result<Self, InventoryValueError> {
        if identity.is_empty() {
            return Err(InventoryValueError::new(
                InventoryValueErrorCode::SpiffeIdentity,
            ));
        }
        self.spiffe_identity = Some(identity.into());
        Ok(self)
    }
}
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum RuntimePlacementMode {
    Local,
    Remote,
}
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum RuntimePlacementReadiness {
    Ready,
    MutualTlsSourceUnavailable,
}

impl RuntimeDomain {
    const fn canonical_rank(self) -> u8 {
        match self {
            Self::Identity => 0,
            Self::Settings => 1,
            Self::Audit => 2,
            Self::ContractRegistry => 3,
            Self::SystemHealth => 4,
        }
    }
}

#[derive(Clone, Copy, Eq, PartialEq)]
pub struct InventoryValueError(InventoryValueErrorCode);
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[non_exhaustive]
pub enum InventoryValueErrorCode {
    Fingerprint,
    SourceRevision,
    DomainsEmpty,
    DomainsDuplicate,
    Identifier,
    Endpoint,
    Workflow,
    WorkflowsDuplicate,
    ListenersNotCanonical,
    ProvidersNotCanonical,
    PlacementsNotCanonical,
    SpiffeIdentity,
}
impl InventoryValueError {
    const fn new(code: InventoryValueErrorCode) -> Self {
        Self(code)
    }
    pub const fn code(self) -> InventoryValueErrorCode {
        self.0
    }
}
impl fmt::Debug for InventoryValueError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str("invalid runtime inventory value")
    }
}
impl fmt::Display for InventoryValueError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str("invalid runtime inventory value")
    }
}
impl Error for InventoryValueError {}

fn has_duplicates<T>(values: &[T], equal: impl Fn(&T, &T) -> bool) -> bool {
    values
        .iter()
        .enumerate()
        .any(|(index, value)| values[index + 1..].iter().any(|other| equal(value, other)))
}

fn strictly_ordered_by<T>(values: &[T], key: impl Fn(&T) -> &str) -> bool {
    values.windows(2).all(|pair| key(&pair[0]) < key(&pair[1]))
}
