[package]
name = "journeys"
version = "0.0.0"
edition = "2024"
publish = false
autolib = false

[[test]]
name = "localtx_validation_journey"
path = "tests/localtx_validation_journey.rs"
required-features = ["integration"]

[dev-dependencies]
generated = { path = "../generated" }
vocab = { path = "../crates/vocab" }

[features]
integration = []
