[package]
name = "amqp-integration"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dev-dependencies]
rss-contract.workspace = true
amqp = { path = "../../adapters/amqp", features = ["integration"] }
anyhow = { workspace = true }
rss-runtime.workspace = true
rss-transactional-messaging = { workspace = true }
rss-transactional-messaging-runtime.workspace = true
rss-request-context = { workspace = true }
secure = { path = "../../crates/secure" }
testkit = { path = "../../crates/testkit", features = ["containers"] }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "sync", "time"] }

[lints]
workspace = true
