//! Provider-neutral `RevocationStore` conformance.
//!
//! The helper owns no RSS types: adapters provide opaque scope/serial/expiry values plus boxed
//! async operations. This keeps testkit free of workspace dependencies while making the security
//! semantics executable by every implementation.

use std::fmt::Debug;
use std::future::Future;
use std::pin::Pin;

/// Boxed async operation used to adapt a provider without adding an async-trait dependency.
pub type RevocationFuture<'a, T> = Pin<Box<dyn Future<Output = T> + Send + 'a>>;

/// Canonical values needed by [`assert_revocation_semantics`].
#[derive(Clone, Debug)]
pub struct RevocationCases<Scope, Serial, Expiry> {
    pub primary_scope: Scope,
    pub other_tenant_scope: Scope,
    pub other_device_scope: Scope,
    pub primary_serial: Serial,
    pub rotated_serial: Serial,
    /// A key reserved for first-insert concurrency; it must differ from the other serials.
    pub concurrent_serial: Serial,
    /// A key reserved for racing different expiries on the first insert.
    pub concurrent_conflict_serial: Serial,
    /// A key reserved for rejecting an already-expired certificate without aliasing an existing
    /// record. It must differ from every serial used by the other scenarios.
    pub expired_serial: Serial,
    pub valid_expiry: Expiry,
    pub conflicting_expiry: Expiry,
    pub expired_expiry: Expiry,
}

/// Provider-private evidence used to prove one logical revocation maps to one stable record.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct RevocationEvidence<Marker> {
    /// Number of physical records for the exact scope and serial.
    pub record_count: usize,
    /// Marker generated by the provider for the first persisted revocation, normally `revoked_at`.
    pub first_revoked_marker: Option<Marker>,
}

/// A provider violated the closed revocation behavior contract.
#[derive(Debug, thiserror::Error)]
#[non_exhaustive]
pub enum RevocationConformanceError {
    #[error("revocation conformance provider operation failed during {stage}")]
    Provider { stage: &'static str },
    #[error("revocation conformance expected an error during {stage}")]
    ExpectedError { stage: &'static str },
    #[error(
        "revocation conformance visibility mismatch during {stage}: expected {expected}, got {actual}"
    )]
    Visibility {
        stage: &'static str,
        expected: bool,
        actual: bool,
    },
    #[error("revocation conformance first-revoked marker changed during {stage}")]
    MarkerChanged { stage: &'static str },
    #[error(
        "revocation conformance evidence count mismatch during {stage}: expected {expected}, got {actual}"
    )]
    EvidenceCount {
        stage: &'static str,
        expected: usize,
        actual: usize,
    },
    #[error("revocation conformance fixture aliases values required to be distinct")]
    InvalidFixture,
}

fn visibility(
    stage: &'static str,
    actual: bool,
    expected: bool,
) -> Result<(), RevocationConformanceError> {
    if actual == expected {
        Ok(())
    } else {
        Err(RevocationConformanceError::Visibility {
            stage,
            expected,
            actual,
        })
    }
}

async fn query<Store, Scope, Serial, Error, IsRevoked>(
    stage: &'static str,
    store: &Store,
    scope: Scope,
    serial: Serial,
    expected: bool,
    is_revoked: &IsRevoked,
) -> Result<(), RevocationConformanceError>
where
    IsRevoked: for<'a> Fn(&'a Store, Serial, Scope) -> RevocationFuture<'a, Result<bool, Error>>,
{
    let actual = is_revoked(store, serial, scope)
        .await
        .map_err(|_| RevocationConformanceError::Provider { stage })?;
    visibility(stage, actual, expected)
}

fn validate_cases<Scope, Serial, Expiry>(
    cases: &RevocationCases<Scope, Serial, Expiry>,
) -> Result<(), RevocationConformanceError>
where
    Scope: PartialEq,
    Serial: PartialEq,
    Expiry: PartialEq,
{
    let scopes_are_distinct = cases.primary_scope != cases.other_tenant_scope
        && cases.primary_scope != cases.other_device_scope
        && cases.other_tenant_scope != cases.other_device_scope;
    let serials_are_distinct = cases.primary_serial != cases.rotated_serial
        && cases.primary_serial != cases.concurrent_serial
        && cases.primary_serial != cases.concurrent_conflict_serial
        && cases.primary_serial != cases.expired_serial
        && cases.rotated_serial != cases.concurrent_serial
        && cases.rotated_serial != cases.concurrent_conflict_serial
        && cases.rotated_serial != cases.expired_serial
        && cases.concurrent_serial != cases.concurrent_conflict_serial
        && cases.concurrent_serial != cases.expired_serial
        && cases.concurrent_conflict_serial != cases.expired_serial;
    let expiries_are_distinct = cases.valid_expiry != cases.conflicting_expiry
        && cases.valid_expiry != cases.expired_expiry
        && cases.conflicting_expiry != cases.expired_expiry;
    if scopes_are_distinct && serials_are_distinct && expiries_are_distinct {
        Ok(())
    } else {
        Err(RevocationConformanceError::InvalidFixture)
    }
}

async fn assert_round_trip_and_idempotency<Store, Scope, Serial, Expiry, Marker, Error, R, I, E>(
    store: &Store,
    cases: &RevocationCases<Scope, Serial, Expiry>,
    revoke: &R,
    is_revoked: &I,
    evidence: &E,
) -> Result<(), RevocationConformanceError>
where
    Scope: Clone,
    Serial: Clone,
    Expiry: Clone,
    Marker: Eq,
    R: for<'a> Fn(&'a Store, Serial, Scope, Expiry) -> RevocationFuture<'a, Result<(), Error>>,
    I: for<'a> Fn(&'a Store, Serial, Scope) -> RevocationFuture<'a, Result<bool, Error>>,
    E: for<'a> Fn(
        &'a Store,
        Serial,
        Scope,
    ) -> RevocationFuture<'a, Result<RevocationEvidence<Marker>, Error>>,
{
    query(
        "initial miss",
        store,
        cases.primary_scope.clone(),
        cases.primary_serial.clone(),
        false,
        is_revoked,
    )
    .await?;
    revoke(
        store,
        cases.primary_serial.clone(),
        cases.primary_scope.clone(),
        cases.valid_expiry.clone(),
    )
    .await
    .map_err(|_| RevocationConformanceError::Provider {
        stage: "round-trip revoke",
    })?;
    for (stage, scope, serial, expected) in [
        (
            "round-trip hit",
            cases.primary_scope.clone(),
            cases.primary_serial.clone(),
            true,
        ),
        (
            "tenant isolation",
            cases.other_tenant_scope.clone(),
            cases.primary_serial.clone(),
            false,
        ),
        (
            "device isolation",
            cases.other_device_scope.clone(),
            cases.primary_serial.clone(),
            false,
        ),
        (
            "serial isolation",
            cases.primary_scope.clone(),
            cases.rotated_serial.clone(),
            false,
        ),
    ] {
        query(stage, store, scope, serial, expected, is_revoked).await?;
    }

    let first = evidence(
        store,
        cases.primary_serial.clone(),
        cases.primary_scope.clone(),
    )
    .await
    .map_err(|_| RevocationConformanceError::Provider {
        stage: "first revoked marker",
    })?;
    if first.record_count != 1 {
        return Err(RevocationConformanceError::EvidenceCount {
            stage: "first revoked evidence",
            expected: 1,
            actual: first.record_count,
        });
    }
    if first.first_revoked_marker.is_none() {
        return Err(RevocationConformanceError::MarkerChanged {
            stage: "missing first revoked marker",
        });
    }
    revoke(
        store,
        cases.primary_serial.clone(),
        cases.primary_scope.clone(),
        cases.valid_expiry.clone(),
    )
    .await
    .map_err(|_| RevocationConformanceError::Provider {
        stage: "idempotent duplicate",
    })?;
    let duplicate = evidence(
        store,
        cases.primary_serial.clone(),
        cases.primary_scope.clone(),
    )
    .await
    .map_err(|_| RevocationConformanceError::Provider {
        stage: "duplicate revoked marker",
    })?;
    if duplicate.record_count != 1 {
        return Err(RevocationConformanceError::EvidenceCount {
            stage: "idempotent duplicate",
            expected: 1,
            actual: duplicate.record_count,
        });
    }
    if first.first_revoked_marker == duplicate.first_revoked_marker {
        Ok(())
    } else {
        Err(RevocationConformanceError::MarkerChanged {
            stage: "idempotent duplicate",
        })
    }
}

async fn assert_concurrent_first_insert<Store, Scope, Serial, Expiry, Marker, Error, R, I, E>(
    store: &Store,
    cases: &RevocationCases<Scope, Serial, Expiry>,
    revoke: &R,
    is_revoked: &I,
    evidence: &E,
) -> Result<(), RevocationConformanceError>
where
    Store: Sync,
    Scope: Clone,
    Serial: Clone,
    Expiry: Clone,
    R: for<'a> Fn(&'a Store, Serial, Scope, Expiry) -> RevocationFuture<'a, Result<(), Error>>
        + Sync,
    I: for<'a> Fn(&'a Store, Serial, Scope) -> RevocationFuture<'a, Result<bool, Error>>,
    Marker: Eq,
    E: for<'a> Fn(
        &'a Store,
        Serial,
        Scope,
    ) -> RevocationFuture<'a, Result<RevocationEvidence<Marker>, Error>>,
{
    let left = revoke(
        store,
        cases.concurrent_serial.clone(),
        cases.primary_scope.clone(),
        cases.valid_expiry.clone(),
    );
    let right = revoke(
        store,
        cases.concurrent_serial.clone(),
        cases.primary_scope.clone(),
        cases.valid_expiry.clone(),
    );
    let (left, right) = futures::future::join(left, right).await;
    left.map_err(|_| RevocationConformanceError::Provider {
        stage: "concurrent duplicate left",
    })?;
    right.map_err(|_| RevocationConformanceError::Provider {
        stage: "concurrent duplicate right",
    })?;
    query(
        "concurrent duplicate hit",
        store,
        cases.primary_scope.clone(),
        cases.concurrent_serial.clone(),
        true,
        is_revoked,
    )
    .await?;

    let first = evidence(
        store,
        cases.concurrent_serial.clone(),
        cases.primary_scope.clone(),
    )
    .await
    .map_err(|_| RevocationConformanceError::Provider {
        stage: "concurrent first evidence",
    })?;
    if first.record_count != 1 {
        return Err(RevocationConformanceError::EvidenceCount {
            stage: "concurrent first insert",
            expected: 1,
            actual: first.record_count,
        });
    }
    if first.first_revoked_marker.is_none() {
        return Err(RevocationConformanceError::MarkerChanged {
            stage: "missing concurrent first marker",
        });
    }

    revoke(
        store,
        cases.concurrent_serial.clone(),
        cases.primary_scope.clone(),
        cases.valid_expiry.clone(),
    )
    .await
    .map_err(|_| RevocationConformanceError::Provider {
        stage: "concurrent idempotent replay",
    })?;
    let replay = evidence(
        store,
        cases.concurrent_serial.clone(),
        cases.primary_scope.clone(),
    )
    .await
    .map_err(|_| RevocationConformanceError::Provider {
        stage: "concurrent replay evidence",
    })?;
    if replay.record_count != 1 {
        return Err(RevocationConformanceError::EvidenceCount {
            stage: "concurrent idempotent replay",
            expected: 1,
            actual: replay.record_count,
        });
    }
    if first.first_revoked_marker != replay.first_revoked_marker {
        return Err(RevocationConformanceError::MarkerChanged {
            stage: "concurrent idempotent replay",
        });
    }
    assert_concurrent_conflicting_first_insert(store, cases, revoke, is_revoked, evidence).await
}

async fn assert_concurrent_conflicting_first_insert<
    Store,
    Scope,
    Serial,
    Expiry,
    Marker,
    Error,
    R,
    I,
    E,
>(
    store: &Store,
    cases: &RevocationCases<Scope, Serial, Expiry>,
    revoke: &R,
    is_revoked: &I,
    evidence: &E,
) -> Result<(), RevocationConformanceError>
where
    Store: Sync,
    Scope: Clone,
    Serial: Clone,
    Expiry: Clone,
    Marker: Eq,
    R: for<'a> Fn(&'a Store, Serial, Scope, Expiry) -> RevocationFuture<'a, Result<(), Error>>
        + Sync,
    I: for<'a> Fn(&'a Store, Serial, Scope) -> RevocationFuture<'a, Result<bool, Error>>,
    E: for<'a> Fn(
        &'a Store,
        Serial,
        Scope,
    ) -> RevocationFuture<'a, Result<RevocationEvidence<Marker>, Error>>,
{
    let left = revoke(
        store,
        cases.concurrent_conflict_serial.clone(),
        cases.primary_scope.clone(),
        cases.valid_expiry.clone(),
    );
    let right = revoke(
        store,
        cases.concurrent_conflict_serial.clone(),
        cases.primary_scope.clone(),
        cases.conflicting_expiry.clone(),
    );
    let (left, right) = futures::future::join(left, right).await;
    let (winner_expiry, loser_expiry) = match (left, right) {
        (Ok(()), Err(_)) => (cases.valid_expiry.clone(), cases.conflicting_expiry.clone()),
        (Err(_), Ok(())) => (cases.conflicting_expiry.clone(), cases.valid_expiry.clone()),
        (Ok(()), Ok(())) | (Err(_), Err(_)) => {
            return Err(RevocationConformanceError::ExpectedError {
                stage: "concurrent conflicting first insert must have one winner",
            });
        }
    };
    query(
        "concurrent conflicting winner hit",
        store,
        cases.primary_scope.clone(),
        cases.concurrent_conflict_serial.clone(),
        true,
        is_revoked,
    )
    .await?;

    let first = evidence(
        store,
        cases.concurrent_conflict_serial.clone(),
        cases.primary_scope.clone(),
    )
    .await
    .map_err(|_| RevocationConformanceError::Provider {
        stage: "concurrent conflicting first evidence",
    })?;
    if first.record_count != 1 {
        return Err(RevocationConformanceError::EvidenceCount {
            stage: "concurrent conflicting first insert",
            expected: 1,
            actual: first.record_count,
        });
    }
    if first.first_revoked_marker.is_none() {
        return Err(RevocationConformanceError::MarkerChanged {
            stage: "concurrent conflicting first insert",
        });
    }
    revoke(
        store,
        cases.concurrent_conflict_serial.clone(),
        cases.primary_scope.clone(),
        winner_expiry,
    )
    .await
    .map_err(|_| RevocationConformanceError::Provider {
        stage: "concurrent conflicting winner replay",
    })?;
    if revoke(
        store,
        cases.concurrent_conflict_serial.clone(),
        cases.primary_scope.clone(),
        loser_expiry,
    )
    .await
    .is_ok()
    {
        return Err(RevocationConformanceError::ExpectedError {
            stage: "concurrent conflicting loser replay",
        });
    }
    let replay = evidence(
        store,
        cases.concurrent_conflict_serial.clone(),
        cases.primary_scope.clone(),
    )
    .await
    .map_err(|_| RevocationConformanceError::Provider {
        stage: "concurrent conflicting replay evidence",
    })?;
    if replay.record_count != 1 {
        return Err(RevocationConformanceError::EvidenceCount {
            stage: "concurrent conflicting replay",
            expected: 1,
            actual: replay.record_count,
        });
    }
    if first.first_revoked_marker == replay.first_revoked_marker {
        Ok(())
    } else {
        Err(RevocationConformanceError::MarkerChanged {
            stage: "concurrent conflicting replay",
        })
    }
}

#[allow(clippy::too_many_arguments)]
async fn assert_conflict_rotation_and_expiry<Store, Scope, Serial, Expiry, Error, R, I, A>(
    store: &Store,
    expired_store: &Store,
    cases: &RevocationCases<Scope, Serial, Expiry>,
    revoke: &R,
    is_revoked: &I,
    advance_past_expiry: &A,
) -> Result<(), RevocationConformanceError>
where
    Scope: Clone,
    Serial: Clone,
    Expiry: Clone,
    R: for<'a> Fn(&'a Store, Serial, Scope, Expiry) -> RevocationFuture<'a, Result<(), Error>>,
    I: for<'a> Fn(&'a Store, Serial, Scope) -> RevocationFuture<'a, Result<bool, Error>>,
    A: for<'a> Fn(&'a Store) -> RevocationFuture<'a, ()>,
{
    if revoke(
        store,
        cases.primary_serial.clone(),
        cases.primary_scope.clone(),
        cases.conflicting_expiry.clone(),
    )
    .await
    .is_ok()
    {
        return Err(RevocationConformanceError::ExpectedError {
            stage: "conflicting expiry",
        });
    }
    if revoke(
        expired_store,
        cases.expired_serial.clone(),
        cases.primary_scope.clone(),
        cases.expired_expiry.clone(),
    )
    .await
    .is_ok()
    {
        return Err(RevocationConformanceError::ExpectedError {
            stage: "expired not-after",
        });
    }
    revoke(
        store,
        cases.rotated_serial.clone(),
        cases.primary_scope.clone(),
        cases.valid_expiry.clone(),
    )
    .await
    .map_err(|_| RevocationConformanceError::Provider {
        stage: "rotated serial revoke",
    })?;
    query(
        "rotated serial independent hit",
        store,
        cases.primary_scope.clone(),
        cases.rotated_serial.clone(),
        true,
        is_revoked,
    )
    .await?;
    advance_past_expiry(store).await;
    query(
        "logical expiry",
        store,
        cases.primary_scope.clone(),
        cases.primary_serial.clone(),
        false,
        is_revoked,
    )
    .await
}

/// Assert the complete provider-independent revocation semantics.
///
/// `advance_past_expiry` moves the provider's authoritative clock beyond `valid_expiry`; it may
/// sleep for a real database or advance an injected clock. `evidence` reads provider-private row
/// count and marker data used only to prove duplicate/concurrent writes preserve one `revoked_at`.
#[allow(clippy::too_many_arguments)]
pub async fn assert_revocation_semantics<
    Store,
    Scope,
    Serial,
    Expiry,
    Marker,
    Error,
    Make,
    Revoke,
    IsRevoked,
    Evidence,
    Advance,
>(
    make: Make,
    cases: RevocationCases<Scope, Serial, Expiry>,
    revoke: Revoke,
    is_revoked: IsRevoked,
    evidence: Evidence,
    advance_past_expiry: Advance,
) -> Result<(), RevocationConformanceError>
where
    Store: Sync,
    Scope: Clone + PartialEq + Send,
    Serial: Clone + PartialEq + Send,
    Expiry: Clone + PartialEq + Send,
    Marker: Debug + Eq,
    Make: Fn() -> Store,
    Revoke: for<'a> Fn(&'a Store, Serial, Scope, Expiry) -> RevocationFuture<'a, Result<(), Error>>
        + Sync,
    IsRevoked:
        for<'a> Fn(&'a Store, Serial, Scope) -> RevocationFuture<'a, Result<bool, Error>> + Sync,
    Evidence: for<'a> Fn(
            &'a Store,
            Serial,
            Scope,
        ) -> RevocationFuture<'a, Result<RevocationEvidence<Marker>, Error>>
        + Sync,
    Advance: for<'a> Fn(&'a Store) -> RevocationFuture<'a, ()>,
{
    validate_cases(&cases)?;
    let store = make();
    assert_round_trip_and_idempotency(&store, &cases, &revoke, &is_revoked, &evidence).await?;
    let concurrent_store = make();
    assert_concurrent_first_insert(&concurrent_store, &cases, &revoke, &is_revoked, &evidence)
        .await?;
    let expired_store = make();
    assert_conflict_rotation_and_expiry(
        &store,
        &expired_store,
        &cases,
        &revoke,
        &is_revoked,
        &advance_past_expiry,
    )
    .await
}

/// Prove that read and write storage faults remain errors rather than becoming misses/successes.
pub async fn assert_storage_errors_propagate<Read, Write, ReadError, WriteError>(
    read: Read,
    write: Write,
) -> Result<(), RevocationConformanceError>
where
    Read: Future<Output = Result<bool, ReadError>>,
    Write: Future<Output = Result<(), WriteError>>,
{
    if read.await.is_ok() {
        return Err(RevocationConformanceError::ExpectedError {
            stage: "storage read fault",
        });
    }
    if write.await.is_ok() {
        return Err(RevocationConformanceError::ExpectedError {
            stage: "storage write fault",
        });
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::{
        RevocationCases, RevocationEvidence, assert_revocation_semantics,
        assert_storage_errors_propagate,
    };
    use std::collections::HashMap;
    use std::sync::atomic::{AtomicU64, Ordering};
    use std::sync::{Arc, Mutex, PoisonError};

    #[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
    struct Scope {
        tenant: u8,
        device: u8,
    }

    #[derive(Debug)]
    struct Fake {
        now: AtomicU64,
        sequence: AtomicU64,
        records: Arc<Mutex<HashMap<FakeKey, Vec<FakeRecord>>>>,
        ignore_device: bool,
        ignore_expiry: bool,
        accept_conflict: bool,
        accept_concurrent_conflict_serial: Option<u8>,
        append_duplicate_serial: Option<u8>,
        overwrite_marker_serial: Option<u8>,
    }

    #[derive(Debug)]
    struct FakeError;

    type FakeKey = (u8, u8, u8);
    type FakeRecord = (u64, u64);

    impl Fake {
        fn sound() -> Self {
            Self::with_defects(false, false, false)
        }

        fn with_defects(ignore_device: bool, ignore_expiry: bool, accept_conflict: bool) -> Self {
            Self {
                now: AtomicU64::new(10),
                sequence: AtomicU64::new(0),
                records: Arc::new(Mutex::new(HashMap::new())),
                ignore_device,
                ignore_expiry,
                accept_conflict,
                accept_concurrent_conflict_serial: None,
                append_duplicate_serial: None,
                overwrite_marker_serial: None,
            }
        }

        fn appending_duplicate_evidence(serial: u8) -> Self {
            Self {
                append_duplicate_serial: Some(serial),
                ..Self::sound()
            }
        }

        fn accepting_concurrent_conflict(serial: u8) -> Self {
            Self {
                accept_concurrent_conflict_serial: Some(serial),
                ..Self::sound()
            }
        }

        fn overwriting_duplicate_marker(serial: u8) -> Self {
            Self {
                overwrite_marker_serial: Some(serial),
                ..Self::sound()
            }
        }

        fn shared_without_expiry_validation(
            records: Arc<Mutex<HashMap<FakeKey, Vec<FakeRecord>>>>,
        ) -> Self {
            Self {
                records,
                ignore_expiry: true,
                ..Self::sound()
            }
        }

        fn key(&self, scope: Scope, serial: u8) -> (u8, u8, u8) {
            (
                scope.tenant,
                if self.ignore_device { 0 } else { scope.device },
                serial,
            )
        }

        async fn revoke(&self, serial: u8, scope: Scope, expiry: u64) -> Result<(), FakeError> {
            if !self.ignore_expiry && expiry <= self.now.load(Ordering::SeqCst) {
                return Err(FakeError);
            }
            let mut records = self.records.lock().unwrap_or_else(PoisonError::into_inner);
            let key = self.key(scope, serial);
            if let Some(existing) = records.get_mut(&key) {
                if existing
                    .first()
                    .is_some_and(|(stored_expiry, _)| *stored_expiry != expiry)
                    && !self.accept_conflict
                    && self.accept_concurrent_conflict_serial != Some(serial)
                {
                    return Err(FakeError);
                }
                if self.append_duplicate_serial == Some(serial) {
                    let marker = self.sequence.fetch_add(1, Ordering::SeqCst);
                    existing.push((expiry, marker));
                } else if self.overwrite_marker_serial == Some(serial) {
                    let marker = self.sequence.fetch_add(1, Ordering::SeqCst);
                    if let Some(record) = existing.first_mut() {
                        record.1 = marker;
                    }
                }
                return Ok(());
            }
            let marker = self.sequence.fetch_add(1, Ordering::SeqCst);
            records.insert(key, vec![(expiry, marker)]);
            Ok(())
        }

        async fn is_revoked(&self, serial: u8, scope: Scope) -> Result<bool, FakeError> {
            let now = self.now.load(Ordering::SeqCst);
            let records = self.records.lock().unwrap_or_else(PoisonError::into_inner);
            Ok(records
                .get(&self.key(scope, serial))
                .and_then(|records| records.first())
                .is_some_and(|(expiry, _)| self.ignore_expiry || *expiry > now))
        }

        async fn evidence(
            &self,
            serial: u8,
            scope: Scope,
        ) -> Result<RevocationEvidence<u64>, FakeError> {
            let records = self.records.lock().unwrap_or_else(PoisonError::into_inner);
            let matching = records.get(&self.key(scope, serial));
            Ok(RevocationEvidence {
                record_count: matching.map_or(0, Vec::len),
                first_revoked_marker: matching
                    .and_then(|records| records.first())
                    .map(|(_, marker)| *marker),
            })
        }
    }

    fn cases() -> RevocationCases<Scope, u8, u64> {
        RevocationCases {
            primary_scope: Scope {
                tenant: 1,
                device: 1,
            },
            other_tenant_scope: Scope {
                tenant: 2,
                device: 1,
            },
            other_device_scope: Scope {
                tenant: 1,
                device: 2,
            },
            primary_serial: 1,
            rotated_serial: 2,
            concurrent_serial: 3,
            concurrent_conflict_serial: 4,
            expired_serial: 5,
            valid_expiry: 20,
            conflicting_expiry: 21,
            expired_expiry: 10,
        }
    }

    async fn run(make: impl Fn() -> Fake) -> Result<(), super::RevocationConformanceError> {
        assert_revocation_semantics(
            make,
            cases(),
            |store, serial, scope, expiry| Box::pin(store.revoke(serial, scope, expiry)),
            |store, serial, scope| Box::pin(store.is_revoked(serial, scope)),
            |store, serial, scope| Box::pin(store.evidence(serial, scope)),
            |store| {
                Box::pin(async move {
                    store.now.store(20, Ordering::SeqCst);
                })
            },
        )
        .await
    }

    #[tokio::test]
    async fn revocation_sound_fake_passes() {
        assert!(run(Fake::sound).await.is_ok());
    }

    #[tokio::test]
    async fn revocation_broken_fake_ignoring_device_is_rejected() {
        assert!(
            run(|| Fake::with_defects(true, false, false))
                .await
                .is_err()
        );
    }

    #[tokio::test]
    async fn revocation_broken_fake_ignoring_expiry_is_rejected() {
        assert!(
            run(|| Fake::with_defects(false, true, false))
                .await
                .is_err()
        );
    }

    #[tokio::test]
    async fn revocation_broken_fake_accepting_conflicting_expiry_is_rejected() {
        assert!(
            run(|| Fake::with_defects(false, false, true))
                .await
                .is_err()
        );
    }

    #[tokio::test]
    async fn revocation_broken_fake_accepting_concurrent_first_write_conflict_is_rejected() {
        assert!(
            run(|| Fake::accepting_concurrent_conflict(4))
                .await
                .is_err()
        );
    }

    #[tokio::test]
    async fn revocation_broken_fake_appending_concurrent_evidence_is_rejected() {
        assert!(run(|| Fake::appending_duplicate_evidence(3)).await.is_err());
    }

    #[tokio::test]
    async fn revocation_broken_fake_overwriting_concurrent_marker_is_rejected() {
        assert!(run(|| Fake::overwriting_duplicate_marker(3)).await.is_err());
    }

    #[tokio::test]
    async fn revocation_broken_fake_rejecting_expired_only_via_existing_conflict_is_rejected() {
        let records = Arc::new(Mutex::new(HashMap::new()));
        assert!(
            run(|| Fake::shared_without_expiry_validation(Arc::clone(&records)))
                .await
                .is_err()
        );
    }

    #[tokio::test]
    async fn revocation_broken_fake_swallowing_storage_error_is_rejected() {
        let swallowed_read =
            assert_storage_errors_propagate(async { Ok::<bool, FakeError>(false) }, async {
                Err::<(), FakeError>(FakeError)
            })
            .await;
        assert!(swallowed_read.is_err());

        let swallowed_write =
            assert_storage_errors_propagate(async { Err::<bool, FakeError>(FakeError) }, async {
                Ok::<(), FakeError>(())
            })
            .await;
        assert!(swallowed_write.is_err());
    }
}
