[package]
name = "deviceloop"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
rss-request-context.workspace = true
vocab = { path = "../vocab" }
ids = { path = "../ids" }
secure = { path = "../secure" }
support = { path = "../support" }
runctx = { path = "../runctx" }
consistency = { path = "../consistency" }
primitives = { path = "../primitives" }
diport = { path = "../diport" }
thiserror = { workspace = true }
