[package]
name = "assembly-schema"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[lib]
name = "assembly_schema"
path = "src/lib.rs"

[features]
default = []
test-support = []

[dependencies]
schemars = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde_path_to_error = { workspace = true }
serde_json_canonicalizer = { workspace = true }
sha2 = { workspace = true }
toml = { workspace = true }
thiserror = { workspace = true }
vocab = { path = "../vocab" }
runtimeinventorymint = { path = "../runtimeinventorymint" }

[lints]
workspace = true

[dev-dependencies]
anyhow = { workspace = true }
jsonschema = { workspace = true }
trybuild = { workspace = true }
