-- CDC broker-header projection for outbox_log.
--
-- The application writes a single sealed metadata JSON object.  These columns are
-- generated by PostgreSQL so Debezium EventRouter can map them to headers without
-- introducing a second application-side write source.

ALTER TABLE outbox_log
    ADD COLUMN occurred_at text GENERATED ALWAYS AS (metadata ->> 'occurredAt') STORED,
    ADD COLUMN trace text GENERATED ALWAYS AS (metadata ->> 'trace') STORED,
    ADD COLUMN correlation_id text GENERATED ALWAYS AS (metadata ->> 'correlation') STORED;

ALTER TABLE outbox_log
    ADD CONSTRAINT outbox_log_metadata_occurred_at_present CHECK (
        metadata ? 'occurredAt'
        AND jsonb_typeof(metadata -> 'occurredAt') = 'number'
        AND occurred_at ~ '^[0-9]+$'
    ),
    ADD CONSTRAINT outbox_log_trace_valid CHECK (
        NOT (metadata ? 'trace')
        OR (
            jsonb_typeof(metadata -> 'trace') = 'string'
            AND length(trace) > 0
            AND octet_length(trace) <= 512
        )
    ),
    ADD CONSTRAINT outbox_log_correlation_id_valid CHECK (
        NOT (metadata ? 'correlation')
        OR (
            jsonb_typeof(metadata -> 'correlation') = 'string'
            AND length(correlation_id) > 0
            AND octet_length(correlation_id) <= 256
        )
    );
