[package]
name = "rss-transactional-messaging-postgres"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish = ["crates-io"]
license-file = "../../LICENSE"
repository.workspace = true
readme = "README.md"
description = "PostgreSQL transactions, inbox and outbox for RSS transactional messaging"

[lints]
workspace = true

[dependencies]
rss-runtime = { workspace = true, optional = true }
rss-transactional-messaging.workspace = true
rss-contract.workspace = true
rss-diag-context = { path = "../diagctx", version = "0.1.0" }
rss-redact.workspace = true
tokio = { workspace = true, features = ["time", "sync", "rt-multi-thread", "macros"] }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
futures = { workspace = true, features = ["std", "async-await", "executor"] }
rss-request-context.workspace = true
rustls.workspace = true
rustls-pki-types.workspace = true
sqlx = { workspace = true, features = ["runtime-tokio", "tls-rustls", "postgres", "macros", "any", "migrate", "json"] }
thiserror = { workspace = true }
tracing.workspace = true
zeroize.workspace = true

[features]
default = []
rss-runtime = ["dep:rss-runtime"]
test-support = []
integration = ["test-support"]

[dev-dependencies]
rcgen = { workspace = true }
trybuild.workspace = true
