[package]
name = "iotdevice"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[[bin]]
name = "iotdevice"
path = "src/main.rs"
test = false

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
deviceloop = { path = "../../crates/deviceloop" }
ids = { path = "../../crates/ids" }
vocab = { path = "../../crates/vocab" }
