[package]
name = "iotdevice"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
rumqttc = { workspace = true, features = ["use-rustls-no-provider"] }
rustls = { workspace = true, features = ["std"] }
rustls-pki-types = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["time"] }
url = { workspace = true }

[dev-dependencies]
static_assertions = { workspace = true }
