// @generated by `cargo xtask codegen`; DO NOT EDIT.
pub(super) const PROJECTION_INPUT_GENERATION: &str =
    "sha256:ff7c69626735495640031695caf9c053830aa6efdcb8c3efa038d68d0cd25801";
pub(super) static PROJECTION_INPUTS: &[super::ProjectionInputIdentity] = &[
    super::ProjectionInputIdentity::from_static(
        "audit.session-projection",
        "v2",
        "sha256:f741f3d37379a56dcafe564b4b7c79d495e8a683534abcc9216cb87a1ab1bf82",
        "identity",
        "identity.session-created",
        "v1",
        "sha256:999d2b098e6c89de6d1841416099942cad21279843456dfc287b1fcaa67a7516",
        "identity.session-created",
    ),
    super::ProjectionInputIdentity::from_static(
        "settings.config-projection",
        "v3",
        "sha256:ce6e2126b5d5831f67955d1db29fc7c0c1cc339cdf4cec1ad2486f5fb778b4d8",
        "settings",
        "settings.config-version-changed",
        "v1",
        "sha256:b74288de6fd13213cb6676431f4833a7c921ec9ffe2825ad244cad49c52d17e4",
        "settings.config-version-changed",
    ),
];
