// @generated by `cargo xtask codegen`; DO NOT EDIT.
pub(super) const PROJECTION_INPUT_GENERATION: &str =
    "sha256:f0c8804d298ce326e5e22b6f8585dbce7cbe794546305cfecd2613985fbeb43e";
pub(super) static PROJECTION_INPUTS: &[super::ProjectionInputIdentity] = &[
    super::ProjectionInputIdentity::from_static(
        "audit.session-projection",
        "v2",
        "sha256:8750ef9b30912c837637ee30ee712e1572903fdaa59514fd486f2d0ab15fa071",
        "identity",
        "identity.session-created",
        "v1",
        "sha256:999d2b098e6c89de6d1841416099942cad21279843456dfc287b1fcaa67a7516",
        "identity.session-created",
    ),
    super::ProjectionInputIdentity::from_static(
        "settings.config-projection",
        "v3",
        "sha256:3504a1f33b4e2765fff012fd263ed9a317d24cbe200382c364e4220d7bf05baa",
        "settings",
        "settings.config-version-changed",
        "v1",
        "sha256:b74288de6fd13213cb6676431f4833a7c921ec9ffe2825ad244cad49c52d17e4",
        "settings.config-version-changed",
    ),
];
