// @generated by `cargo xtask codegen`; DO NOT EDIT.
pub(super) const PROJECTION_INPUT_GENERATION: &str =
    "sha256:0ee8ef28ba5d0d69f12efbf2fa114a5bcfaccec3739c7f97dcc4131ca9890bd0";
pub(super) static PROJECTION_INPUTS: &[super::ProjectionInputIdentity] = &[
    super::ProjectionInputIdentity::from_static(
        "audit.session-projection",
        "v2",
        "sha256:f741f3d37379a56dcafe564b4b7c79d495e8a683534abcc9216cb87a1ab1bf82",
        "identity",
        "identity.session-created",
        "v1",
        "sha256:d8b29c5d222d32205fe78b194bc370eef300c6660a33f68e2ae7d15bebfb7288",
        "identity.session-created",
    ),
    super::ProjectionInputIdentity::from_static(
        "settings.config-projection",
        "v3",
        "sha256:ce6e2126b5d5831f67955d1db29fc7c0c1cc339cdf4cec1ad2486f5fb778b4d8",
        "settings",
        "settings.config-version-changed",
        "v1",
        "sha256:b74288de6fd13213cb6676431f4833a7c921ec9ffe2825ad244cad49c52d17e4",
        "settings.config-version-changed",
    ),
];
