//! `assembly generate-modules` — assembly manifest domain 顺序表 codegen。
//!
//! INVARIANT: ASSEMBLY-MODULES-CODEGEN-01 { level = "Hard", exec = "verify", source = "codegen", golden = "assemblies/runtime/src/generated/modules_gen.rs", synthetic_red = "assembly_codegen::tests::check_rejects_manifest_domain_drift", anti_vacuity = "assembly_codegen::tests::generated_runtime_modules_are_non_empty_and_check_clean" } —— `assembly.toml` 是 domain 组合顺序单源；生成物 committed 并由 verify 字节级守漂移，red/green 测试证明门不恒真。

use anyhow::{Context, Result, bail};
use assembly_schema::{AssemblyDomain, AssemblyManifest, ManifestValidationError};
use sha2::{Digest, Sha256};
use std::fs::{self, File, OpenOptions};
use std::io::{self, Write};
use std::path::{Path, PathBuf};
use std::sync::atomic::{AtomicU64, Ordering};

const MANIFEST_NAME: &str = "assembly.toml";
const GENERATED_REL: &str = "src/generated/modules_gen.rs";
const OWNERSHIP_MARKER: &str =
    "// @generated by `cargo xtask assembly generate-modules`; DO NOT EDIT.";
static TEMP_SEQUENCE: AtomicU64 = AtomicU64::new(0);

struct Target {
    path: PathBuf,
    content: Vec<u8>,
    actual: Option<Vec<u8>>,
}

struct GenerationPlan {
    targets: Vec<Target>,
    owned_orphans: Vec<PathBuf>,
}

pub(crate) fn run(check: bool) -> Result<()> {
    generate_root(&crate::workspace_root()?, check)
}

fn generate_root(root: &Path, check: bool) -> Result<()> {
    let plan = plan_generation(root)?;
    let drift: Vec<&Path> = plan
        .targets
        .iter()
        .filter(|target| target.actual.as_deref() != Some(target.content.as_slice()))
        .map(|target| target.path.as_path())
        .collect();

    if check {
        if drift.is_empty() && plan.owned_orphans.is_empty() {
            eprintln!("assembly generate-modules --check: 无漂移");
            return Ok(());
        }
        for path in &drift {
            eprintln!("  派生漂移: {}", relative_label(root, path));
        }
        for path in &plan.owned_orphans {
            eprintln!("  孤儿派生文件: {}", relative_label(root, path));
        }
        bail!(
            "assembly modules 派生漂移：{} 个目标不一致，{} 个孤儿；运行 `cargo xtask assembly generate-modules`",
            drift.len(),
            plan.owned_orphans.len()
        );
    }

    for target in &plan.targets {
        if target.actual.as_deref() != Some(target.content.as_slice()) {
            ensure_output_path_has_no_symlinks(&target.path)?;
            atomic_write(&target.path, &target.content)
                .with_context(|| format!("原子写入 {} 失败", target.path.display()))?;
            eprintln!("  generated {}", relative_label(root, &target.path));
        }
    }
    for orphan in &plan.owned_orphans {
        ensure_output_path_has_no_symlinks(orphan)?;
        fs::remove_file(orphan).with_context(|| format!("删除孤儿 {} 失败", orphan.display()))?;
        eprintln!("  removed orphan {}", relative_label(root, orphan));
    }
    Ok(())
}

fn plan_generation(root: &Path) -> Result<GenerationPlan> {
    let assemblies_root = root.join("assemblies");
    let mut entries = fs::read_dir(&assemblies_root)
        .with_context(|| format!("读取 {} 失败", assemblies_root.display()))?
        .collect::<io::Result<Vec<_>>>()?;
    entries.sort_by_key(fs::DirEntry::path);

    let mut targets = Vec::new();
    let mut orphan_candidates = Vec::new();
    for entry in entries {
        let file_type = entry
            .file_type()
            .with_context(|| format!("读取 {} 类型失败", entry.path().display()))?;
        if file_type.is_symlink() {
            bail!("assemblies 下禁止符号链接：{}", entry.path().display());
        }
        if !file_type.is_dir() {
            continue;
        }

        let assembly_dir = entry.path();
        let manifest_path = assembly_dir.join(MANIFEST_NAME);
        let output_path = assembly_dir.join(GENERATED_REL);
        reject_symlink(&manifest_path)?;
        ensure_output_path_has_no_symlinks(&output_path)?;
        if !manifest_path.is_file() {
            if output_path.is_file() {
                orphan_candidates.push(output_path);
            }
            continue;
        }

        let source = fs::read(&manifest_path)
            .with_context(|| format!("读取 {} 失败", manifest_path.display()))?;
        let source_text = std::str::from_utf8(&source)
            .with_context(|| format!("{} 不是 UTF-8", manifest_path.display()))?;
        let manifest = AssemblyManifest::from_toml_str(source_text)
            .with_context(|| format!("解析 {} 失败", manifest_path.display()))?;
        let source_label = relative_label(root, &manifest_path);
        ensure_safe_source_label(&source_label)?;
        validate_manifest(&manifest, &source_label)?;
        let content = render_modules(&manifest, &source_label, &source)?;
        let actual = read_owned_target(&output_path)?;
        targets.push(Target {
            path: output_path,
            content: content.into_bytes(),
            actual,
        });
    }

    let mut owned_orphans = Vec::new();
    for path in orphan_candidates {
        let bytes = fs::read(&path).with_context(|| format!("读取 {} 失败", path.display()))?;
        ensure_owned(&path, &bytes)?;
        owned_orphans.push(path);
    }
    owned_orphans.sort();
    Ok(GenerationPlan {
        targets,
        owned_orphans,
    })
}

fn ensure_safe_source_label(source_label: &str) -> Result<()> {
    if source_label.chars().any(char::is_control) {
        bail!("manifest source path 含控制字符，拒绝渲染 generated Rust");
    }
    Ok(())
}

fn validate_manifest(manifest: &AssemblyManifest, source_label: &str) -> Result<()> {
    let Err(errors) = manifest.validate_basic() else {
        return Ok(());
    };
    let details = errors
        .as_slice()
        .iter()
        .map(|error| match error {
            ManifestValidationError::Empty { field } => {
                format!("field={field} empty declaration")
            }
            ManifestValidationError::Duplicate { field } => {
                format!("field={field} duplicate declaration")
            }
        })
        .collect::<Vec<_>>()
        .join("; ");
    bail!("校验 {source_label} 失败：{details}")
}

fn reject_symlink(path: &Path) -> Result<()> {
    match fs::symlink_metadata(path) {
        Ok(metadata) if metadata.file_type().is_symlink() => {
            bail!("生成器路径禁止符号链接：{}", path.display())
        }
        Ok(_) => Ok(()),
        Err(error) if error.kind() == io::ErrorKind::NotFound => Ok(()),
        Err(error) => Err(error).with_context(|| format!("读取 {} 元数据失败", path.display())),
    }
}

fn ensure_output_path_has_no_symlinks(path: &Path) -> Result<()> {
    let generated_dir = path
        .parent()
        .ok_or_else(|| anyhow::anyhow!("{} 无 generated 父目录", path.display()))?;
    let src_dir = generated_dir
        .parent()
        .ok_or_else(|| anyhow::anyhow!("{} 无 src 父目录", path.display()))?;
    let assembly_dir = src_dir
        .parent()
        .ok_or_else(|| anyhow::anyhow!("{} 无 assembly 父目录", path.display()))?;
    for candidate in [assembly_dir, src_dir, generated_dir, path] {
        reject_symlink(candidate)?;
    }
    Ok(())
}

fn read_owned_target(path: &Path) -> Result<Option<Vec<u8>>> {
    if !path.exists() {
        return Ok(None);
    }
    if !path.is_file() {
        bail!("生成目标不是普通文件：{}", path.display());
    }
    let bytes = fs::read(path).with_context(|| format!("读取 {} 失败", path.display()))?;
    ensure_owned(path, &bytes)?;
    Ok(Some(bytes))
}

fn ensure_owned(path: &Path, bytes: &[u8]) -> Result<()> {
    if !bytes.starts_with(OWNERSHIP_MARKER.as_bytes()) {
        bail!(
            "拒绝覆盖或删除非本生成器文件：{}（缺 ownership marker）",
            path.display()
        );
    }
    Ok(())
}

fn render_modules(
    manifest: &AssemblyManifest,
    source_label: &str,
    source: &[u8],
) -> Result<String> {
    let hash = sha256(source);
    let mut code = format!(
        "{OWNERSHIP_MARKER}\n// Source: {source_label}\n// Source-SHA256: {hash}\n\nuse anyhow::Context as _;\nuse bootstrap::DomainBinding;\n\nuse crate::SharedRuntimeDeps;\n\npub async fn wire_domains(deps: &SharedRuntimeDeps) -> anyhow::Result<Vec<DomainBinding>> {{\n    Ok(vec![\n"
    );
    for domain in &manifest.domains {
        let module = module_name(*domain)?;
        code.push_str(&format!(
            "        crate::domains::{module}::module(deps)\n            .await\n            .context(\"wire domain '{module}'\")?,\n"
        ));
    }
    code.push_str("    ])\n}\n\n#[cfg(test)]\npub(crate) async fn wire_test_domains() -> anyhow::Result<Vec<DomainBinding>> {\n    Ok(vec![\n");
    for domain in &manifest.domains {
        let module = module_name(*domain)?;
        code.push_str(&format!(
            "        crate::domains::{module}::tests::test_binding()\n            .await\n            .context(\"wire test domain '{module}'\")?,\n"
        ));
    }
    code.push_str("    ])\n}\n");
    crate::codegen::format_rust(&code)
}

fn module_name(domain: AssemblyDomain) -> Result<&'static str> {
    match domain {
        AssemblyDomain::Identity => Ok("identity"),
        AssemblyDomain::Settings => Ok("settings"),
        AssemblyDomain::Audit => Ok("audit"),
        AssemblyDomain::Contractreg => {
            bail!("domain `contractreg` 尚无 runtime::domains::contractreg::module factory")
        }
        AssemblyDomain::Syshealth => {
            bail!("domain `syshealth` 尚无 runtime::domains::syshealth::module factory")
        }
    }
}

fn sha256(bytes: &[u8]) -> String {
    let digest = Sha256::digest(bytes);
    let mut hex = String::with_capacity(64);
    for byte in digest {
        hex.push_str(&format!("{byte:02x}"));
    }
    format!("sha256:{hex}")
}

fn relative_label(root: &Path, path: &Path) -> String {
    path.strip_prefix(root)
        .unwrap_or(path)
        .components()
        .map(|component| component.as_os_str().to_string_lossy())
        .collect::<Vec<_>>()
        .join("/")
}

fn atomic_write(path: &Path, content: &[u8]) -> Result<()> {
    let parent = path
        .parent()
        .ok_or_else(|| anyhow::anyhow!("{} 无父目录", path.display()))?;
    fs::create_dir_all(parent).with_context(|| format!("创建 {} 失败", parent.display()))?;
    let file_name = path
        .file_name()
        .ok_or_else(|| anyhow::anyhow!("{} 无文件名", path.display()))?
        .to_string_lossy();
    let temp = parent.join(format!(
        ".{file_name}.tmp-{}-{}",
        std::process::id(),
        TEMP_SEQUENCE.fetch_add(1, Ordering::Relaxed)
    ));

    let result = (|| -> Result<()> {
        let mut file = OpenOptions::new()
            .create_new(true)
            .write(true)
            .open(&temp)
            .with_context(|| format!("创建临时文件 {} 失败", temp.display()))?;
        file.write_all(content)?;
        file.flush()?;
        file.sync_all()?;
        drop(file);
        fs::rename(&temp, path)
            .with_context(|| format!("rename {} -> {} 失败", temp.display(), path.display()))?;
        File::open(parent)?.sync_all()?;
        Ok(())
    })();
    if result.is_err() {
        let _ = fs::remove_file(&temp);
    }
    result
}

#[cfg(test)]
mod tests {
    use super::*;

    fn manifest(domains: &str) -> String {
        format!(
            r#"name = "runtime"
profile = "demo"
domains = [{domains}]
topology = "durable-shared"

[[listeners]]
kind = "primary"

[[diportProviders]]
port = "diport::RateLimiter"
provider = "ratelimit::GovernorLimiter"
providerCrate = "ratelimit"
consumer = "httpserve"
lifecycle = "active"
durability = "ephemeral-memory"
purpose = "test"
"#
        )
    }

    fn test_root(prefix: &str) -> Result<PathBuf> {
        let root = crate::testutil::unique_tmp(prefix);
        fs::create_dir_all(root.join("assemblies/runtime"))?;
        Ok(root)
    }

    fn write_manifest(root: &Path, domains: &str) -> Result<()> {
        fs::write(
            root.join("assemblies/runtime/assembly.toml"),
            manifest(domains),
        )?;
        Ok(())
    }

    fn output(root: &Path) -> PathBuf {
        root.join("assemblies/runtime/src/generated/modules_gen.rs")
    }

    #[test]
    fn render_modules_golden_preserves_manifest_order() -> Result<()> {
        let source = manifest(r#""settings", "identity", "audit""#);
        let parsed = AssemblyManifest::from_toml_str(&source)?;
        let rendered = render_modules(
            &parsed,
            "assemblies/runtime/assembly.toml",
            source.as_bytes(),
        )?;
        assert!(rendered.starts_with(OWNERSHIP_MARKER));
        assert!(rendered.contains("// Source: assemblies/runtime/assembly.toml"));
        assert!(rendered.contains("// Source-SHA256: sha256:"));
        assert_eq!(rendered.matches("::module(deps)").count(), 3);
        assert_eq!(rendered.matches(".context(\"wire domain '").count(), 3);
        assert!(rendered.contains("pub(crate) async fn wire_test_domains"));
        assert_eq!(rendered.matches("::tests::test_binding()").count(), 3);
        let identity = rendered
            .find("domains::identity")
            .ok_or_else(|| anyhow::anyhow!("missing identity call"))?;
        let settings = rendered
            .find("domains::settings")
            .ok_or_else(|| anyhow::anyhow!("missing settings call"))?;
        let audit = rendered
            .find("domains::audit")
            .ok_or_else(|| anyhow::anyhow!("missing audit call"))?;
        assert!(settings < identity && identity < audit);
        let test_settings = rendered
            .find("domains::settings::tests::test_binding")
            .ok_or_else(|| anyhow::anyhow!("missing settings test call"))?;
        let test_identity = rendered
            .find("domains::identity::tests::test_binding")
            .ok_or_else(|| anyhow::anyhow!("missing identity test call"))?;
        let test_audit = rendered
            .find("domains::audit::tests::test_binding")
            .ok_or_else(|| anyhow::anyhow!("missing audit test call"))?;
        assert!(test_settings < test_identity && test_identity < test_audit);
        assert!(!rendered.contains("provider"));
        assert!(!rendered.contains("std::env"));
        syn::parse_file(&rendered)?;
        Ok(())
    }

    #[test]
    fn generated_runtime_modules_are_non_empty_and_check_clean() -> Result<()> {
        let root = test_root("assembly-modules-green")?;
        write_manifest(&root, r#""settings", "identity", "audit""#)?;
        generate_root(&root, false)?;
        generate_root(&root, true)?;
        let first = fs::read(output(&root))?;
        generate_root(&root, false)?;
        assert_eq!(fs::read(output(&root))?, first);
        assert!(
            first
                .windows(b"domains::settings".len())
                .any(|w| w == b"domains::settings")
        );
        fs::remove_dir_all(root)?;
        Ok(())
    }

    #[test]
    fn multiple_assemblies_generate_independent_targets() -> Result<()> {
        let root = test_root("assembly-modules-multiple")?;
        write_manifest(&root, r#""identity", "audit""#)?;
        let settingsonly = root.join("assemblies/settingsonly");
        fs::create_dir_all(&settingsonly)?;
        fs::write(
            settingsonly.join("assembly.toml"),
            manifest(r#""settings""#).replace("name = \"runtime\"", "name = \"settingsonly\""),
        )?;
        let identityaudit = root.join("assemblies/identityaudit");
        fs::create_dir_all(&identityaudit)?;
        fs::write(
            identityaudit.join("assembly.toml"),
            manifest(r#""identity", "audit""#)
                .replace("name = \"runtime\"", "name = \"identityaudit\""),
        )?;

        generate_root(&root, false)?;
        generate_root(&root, true)?;

        let runtime = fs::read_to_string(output(&root))?;
        let settings = fs::read_to_string(settingsonly.join("src/generated/modules_gen.rs"))?;
        let identity_audit =
            fs::read_to_string(identityaudit.join("src/generated/modules_gen.rs"))?;
        assert!(runtime.contains("domains::identity"));
        assert!(runtime.contains("domains::audit"));
        assert!(!runtime.contains("domains::settings"));
        assert!(settings.contains("domains::settings"));
        assert!(!settings.contains("domains::identity"));
        assert!(!settings.contains("domains::audit"));
        let identity = identity_audit
            .find("domains::identity")
            .ok_or_else(|| anyhow::anyhow!("identityaudit missing identity"))?;
        let audit = identity_audit
            .find("domains::audit")
            .ok_or_else(|| anyhow::anyhow!("identityaudit missing audit"))?;
        assert!(identity < audit);
        assert!(!identity_audit.contains("domains::settings"));

        fs::write(
            settingsonly.join("assembly.toml"),
            manifest(r#""settings", "audit""#)
                .replace("name = \"runtime\"", "name = \"settingsonly\""),
        )?;
        assert!(generate_root(&root, true).is_err());
        fs::remove_dir_all(root)?;
        Ok(())
    }

    #[test]
    fn check_rejects_manifest_domain_drift() -> Result<()> {
        let root = test_root("assembly-modules-red")?;
        write_manifest(&root, r#""identity", "settings", "audit""#)?;
        generate_root(&root, false)?;
        write_manifest(&root, r#""settings", "identity", "audit""#)?;
        assert!(generate_root(&root, true).is_err());
        fs::remove_dir_all(root)?;
        Ok(())
    }

    #[test]
    fn duplicate_and_unsupported_domains_fail_before_output() -> Result<()> {
        let root = test_root("assembly-modules-invalid")?;
        write_manifest(&root, r#""identity", "identity""#)?;
        let duplicate_error = generate_root(&root, false)
            .err()
            .ok_or_else(|| anyhow::anyhow!("duplicate domains unexpectedly accepted"))?;
        let duplicate_message = format!("{duplicate_error:#}");
        assert!(duplicate_message.contains("field=domains"));
        assert!(duplicate_message.contains("duplicate"));
        assert!(!output(&root).exists());
        write_manifest(&root, r#""contractreg""#)?;
        assert!(generate_root(&root, false).is_err());
        assert!(!output(&root).exists());
        fs::remove_dir_all(root)?;
        Ok(())
    }

    #[cfg(unix)]
    #[test]
    fn source_path_control_characters_are_rejected_before_render() -> Result<()> {
        let root = crate::testutil::unique_tmp("assembly-modules-source-path");
        let injected = root.join("assemblies/evil\ncompile_error!(\"injected\");");
        fs::create_dir_all(&injected)?;
        fs::write(injected.join("assembly.toml"), manifest(r#""identity""#))?;
        let error = generate_root(&root, false)
            .err()
            .ok_or_else(|| anyhow::anyhow!("control-character path unexpectedly accepted"))?;
        assert!(format!("{error:#}").contains("控制字符"));
        fs::remove_dir_all(root)?;
        Ok(())
    }

    #[test]
    fn check_rejects_missing_and_tampered_output_without_repairing() -> Result<()> {
        let root = test_root("assembly-modules-tamper")?;
        write_manifest(&root, r#""identity""#)?;
        assert!(generate_root(&root, true).is_err());
        generate_root(&root, false)?;
        let tampered = format!("{OWNERSHIP_MARKER}\n// tampered\n");
        fs::write(output(&root), &tampered)?;
        assert!(generate_root(&root, true).is_err());
        assert_eq!(fs::read_to_string(output(&root))?, tampered);
        fs::remove_dir_all(root)?;
        Ok(())
    }

    #[test]
    fn owned_orphan_check_fails_and_write_cleans() -> Result<()> {
        let root = crate::testutil::unique_tmp("assembly-modules-orphan");
        let orphan = root.join("assemblies/old/src/generated/modules_gen.rs");
        let orphan_parent = orphan
            .parent()
            .ok_or_else(|| anyhow::anyhow!("orphan path has no parent"))?;
        fs::create_dir_all(orphan_parent)?;
        fs::write(&orphan, format!("{OWNERSHIP_MARKER}\n"))?;
        assert!(generate_root(&root, true).is_err());
        assert!(orphan.exists());
        generate_root(&root, false)?;
        assert!(!orphan.exists());
        fs::remove_dir_all(root)?;
        Ok(())
    }

    #[test]
    fn non_owned_target_is_never_overwritten_or_deleted() -> Result<()> {
        let root = test_root("assembly-modules-non-owned")?;
        write_manifest(&root, r#""identity""#)?;
        let target = output(&root);
        let target_parent = target
            .parent()
            .ok_or_else(|| anyhow::anyhow!("output path has no parent"))?;
        fs::create_dir_all(target_parent)?;
        fs::write(&target, "// handwritten\n")?;
        assert!(generate_root(&root, false).is_err());
        assert_eq!(fs::read_to_string(target)?, "// handwritten\n");
        fs::remove_dir_all(root)?;
        Ok(())
    }

    #[cfg(unix)]
    #[test]
    fn symlink_assembly_is_rejected() -> Result<()> {
        use std::os::unix::fs::symlink;

        let root = crate::testutil::unique_tmp("assembly-modules-symlink");
        fs::create_dir_all(root.join("assemblies"))?;
        let outside = crate::testutil::unique_tmp("assembly-modules-symlink-target");
        fs::create_dir_all(&outside)?;
        symlink(&outside, root.join("assemblies/runtime"))?;
        assert!(generate_root(&root, false).is_err());
        fs::remove_dir_all(root)?;
        fs::remove_dir_all(outside)?;
        Ok(())
    }

    #[cfg(unix)]
    #[test]
    fn symlink_manifest_is_rejected() -> Result<()> {
        use std::os::unix::fs::symlink;

        let root = test_root("assembly-modules-manifest-symlink")?;
        let outside = crate::testutil::unique_tmp("assembly-modules-manifest-target");
        fs::write(&outside, manifest(r#""identity""#))?;
        symlink(&outside, root.join("assemblies/runtime/assembly.toml"))?;
        assert!(generate_root(&root, false).is_err());
        assert!(!output(&root).exists());
        fs::remove_dir_all(root)?;
        fs::remove_file(outside)?;
        Ok(())
    }

    #[cfg(unix)]
    #[test]
    fn symlink_output_parent_is_rejected() -> Result<()> {
        use std::os::unix::fs::symlink;

        let root = test_root("assembly-modules-output-symlink")?;
        write_manifest(&root, r#""identity""#)?;
        let outside = crate::testutil::unique_tmp("assembly-modules-output-target");
        fs::create_dir_all(&outside)?;
        symlink(&outside, root.join("assemblies/runtime/src"))?;
        assert!(generate_root(&root, false).is_err());
        assert!(!outside.join("generated/modules_gen.rs").exists());
        fs::remove_dir_all(root)?;
        fs::remove_dir_all(outside)?;
        Ok(())
    }
}
