//! 契约 schema → committed `generated/` 派生码（typify → prettyplease → rustfmt）。
//!
//! INVARIANT: CODEGEN-DRIFT-01 — committed `generated/src/**` 与 `contracts/` 的派生结果字节一致、
//! 且无孤儿文件（删契约残留）。Medium（CI 门，`cargo xtask codegen --check`）。
//! golden = committed 文件 diff（rust-analyzer `ensure_file_contents` 模式）；
//! anti-vacuity：注入漂移 / 孤儿文件必失（见 `#[cfg(test)]`）。
//!
//! 成形三段：typify（schema→Rust token）→ prettyplease（可读 `///` doc）→ **rustfmt**（与 `cargo fmt`
//! 同一 formatter，令派生文件 rustfmt-canonical，杜绝 `cargo fmt --all` 重排造成漂移）。rustfmt.toml
//! `ignore` 仅 nightly、`#![rustfmt::skip]` 内属性 stable 编不过，故走 rustfmt-as-formatter 守边界。
//!
//! ref: typify typify-impl/src/lib.rs@0.7.0（TypeSpace::new/add_root_schema/to_stream）
//! ref: rust-analyzer xtask/src/codegen.rs@master（ensure_file_contents 漂移门）

use anyhow::{Context, Result, bail};
use schemars::schema::RootSchema;
use std::collections::{BTreeMap, BTreeSet};
use std::path::{Path, PathBuf};
use typify::{TypeSpace, TypeSpaceSettings};

use crate::contract::manifest::Schemas;
use crate::contract::{DiscoveredContract, discover};

/// 入口：生成（`check=false`）或校验漂移（`check=true`）真实仓的 committed 派生码。
pub fn run(check: bool) -> Result<()> {
    let root = crate::workspace_root()?;
    generate(
        &root.join("contracts"),
        &root.join("generated").join("src"),
        check,
    )
}

/// 把 `contracts_root` 派生进 `gen_src`。根可注入便于测试。
pub(crate) fn generate(contracts_root: &Path, gen_src: &Path, check: bool) -> Result<()> {
    let contracts = discover(contracts_root)?;
    let files = render_all(&contracts)?;
    for (rel, code) in &files {
        let formatted = format_rust(code)?; // rustfmt-canonical（同 cargo fmt），见模块 doc
        ensure_file_contents(&gen_src.join(rel), &formatted, check)?;
    }
    let expected: BTreeSet<PathBuf> = files.iter().map(|(rel, _)| gen_src.join(rel)).collect();
    reconcile_orphans(gen_src, &expected, check)?;
    Ok(())
}

/// 渲染全部期望文件（相对 `generated/src` 的路径 → 内容），确定性排序。
fn render_all(contracts: &[DiscoveredContract]) -> Result<Vec<(PathBuf, String)>> {
    let mut files: Vec<(PathBuf, String)> = Vec::new();
    let mut kinds: BTreeMap<String, BTreeSet<String>> = BTreeMap::new();
    for c in contracts {
        let kind_dir = c.manifest.kind.as_dir().to_string();
        let module = module_name(&c.manifest.domain, &c.manifest.version);
        let rel = PathBuf::from(&kind_dir).join(format!("{module}.rs"));
        files.push((rel, render_contract(c)?));
        kinds.entry(kind_dir).or_default().insert(module);
    }
    for (kind_dir, modules) in &kinds {
        files.push((
            PathBuf::from(kind_dir).join("mod.rs"),
            render_mod_rs(modules),
        ));
    }
    files.push((PathBuf::from("lib.rs"), render_lib_rs(kinds.keys())));
    Ok(files)
}

/// 模块名 `{domain}_{version}`（如 `_seed_v1`）——每契约独立模块，跨契约类型名天然无碰撞。
fn module_name(domain: &str, version: &str) -> String {
    format!("{domain}_{version}")
}

/// 单契约的 typify 派生：按声明顺序把 schema 文件喂进一个 TypeSpace。
fn render_contract(c: &DiscoveredContract) -> Result<String> {
    let mut settings = TypeSpaceSettings::default();
    settings.with_struct_builder(false); // 不要 builder 噪声
    let mut space = TypeSpace::new(&settings);
    for schema_file in ordered_schema_files(&c.manifest.schemas) {
        let path = c.dir.join(schema_file);
        let text = std::fs::read_to_string(&path)
            .with_context(|| format!("读 schema {}", path.display()))?;
        let root: RootSchema = serde_json::from_str(&text)
            .with_context(|| format!("解析 schema {}", path.display()))?;
        space
            .add_root_schema(root)
            .map_err(|e| anyhow::anyhow!("typify 派生 {}: {e}", path.display()))?;
    }
    let parsed = syn::parse2::<syn::File>(space.to_stream()).context("syn 解析 typify token 流")?;
    let source = format!(
        "contracts/{}/{}/{}/",
        c.manifest.kind.as_dir(),
        c.manifest.domain,
        c.manifest.version
    );
    Ok(format!(
        "{}{}",
        generated_header(&source),
        prettyplease::unparse(&parsed)
    ))
}

/// schema 文件按确定性顺序（request → response → payload）喂进 TypeSpace。
fn ordered_schema_files(s: &Schemas) -> Vec<&str> {
    [
        s.request.as_deref(),
        s.response.as_deref(),
        s.payload.as_deref(),
    ]
    .into_iter()
    .flatten()
    .collect()
}

/// 文件头：`@generated` 标记。派生码经 typify→prettyplease→rustfmt 三段成形（见模块 doc），勿手改。
fn generated_header(source: &str) -> String {
    format!("// @generated by `cargo xtask codegen` — DO NOT EDIT. Source: {source}\n")
}

fn render_mod_rs(modules: &BTreeSet<String>) -> String {
    let mut s = generated_header("cargo xtask codegen (module funnel)");
    for m in modules {
        s.push_str(&format!("pub mod {m};\n"));
    }
    s
}

fn render_lib_rs<'a>(kinds: impl Iterator<Item = &'a String>) -> String {
    let mut s = String::new();
    s.push_str("//! generated — 契约派生 wire 类型（committed，一等审查材料）。\n");
    s.push_str("//! 由 `cargo xtask codegen` 生成；勿手改。漂移由 `cargo xtask codegen --check` 守（CI 门）。\n");
    for k in kinds {
        s.push_str(&format!("pub mod {k};\n"));
    }
    s
}

/// rust-analyzer 模式：内容一致则 noop；`check` 下漂移即 `bail`；否则写盘（建父目录）。
fn ensure_file_contents(path: &Path, contents: &str, check: bool) -> Result<()> {
    let normalized = normalize(contents);
    let current = std::fs::read_to_string(path).ok();
    if current.as_deref() == Some(normalized.as_str()) {
        return Ok(());
    }
    if check {
        bail!(
            "派生漂移：{} 与 contracts/ 不一致。跑 `cargo xtask codegen` 重生成并提交。",
            path.display()
        );
    }
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent).with_context(|| format!("建目录 {}", parent.display()))?;
    }
    std::fs::write(path, normalized.as_bytes())
        .with_context(|| format!("写 {}", path.display()))?;
    eprintln!("  regenerated {}", path.display());
    Ok(())
}

fn normalize(s: &str) -> String {
    let mut out = s.trim_end().to_string();
    out.push('\n');
    out
}

/// 经 rustfmt 规范化（与 `cargo fmt` 同一 formatter）——派生 committed 文件须 rustfmt-canonical，
/// 否则 `cargo fmt --all` 会重排 prettyplease 输出（如 `fn fmt(..)` 换行）造成 codegen 漂移。
/// 用 rust-toolchain.toml 钉的 rustfmt（component）；edition 显式 2024 与 generated crate 一致。
fn format_rust(code: &str) -> Result<String> {
    use std::io::Write;
    use std::process::{Command, Stdio};
    let mut child = Command::new("rustfmt")
        .args(["--edition", "2024"])
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .context("spawn rustfmt（需 rustfmt component，见 rust-toolchain.toml）")?;
    let mut stdin = child.stdin.take().context("rustfmt stdin 不可用")?;
    stdin
        .write_all(code.as_bytes())
        .context("写 rustfmt stdin")?;
    drop(stdin); // 关闭 stdin → rustfmt 读到 EOF
    let out = child.wait_with_output().context("等待 rustfmt")?;
    if !out.status.success() {
        bail!("rustfmt 失败: {}", String::from_utf8_lossy(&out.stderr));
    }
    String::from_utf8(out.stdout).context("rustfmt 输出非 UTF-8")
}

/// 孤儿检测：`gen_src` 下任何非期望 `.rs`（删契约残留）。`check` 下 `bail`；否则删除。
fn reconcile_orphans(gen_src: &Path, expected: &BTreeSet<PathBuf>, check: bool) -> Result<()> {
    let mut actual = Vec::new();
    collect_rs_files(gen_src, &mut actual)?;
    let mut orphans: Vec<PathBuf> = actual
        .into_iter()
        .filter(|p| !expected.contains(p))
        .collect();
    orphans.sort();
    if orphans.is_empty() {
        return Ok(());
    }
    if check {
        for o in &orphans {
            eprintln!("  孤儿派生文件: {}", o.display());
        }
        bail!(
            "派生漂移：{} 个孤儿文件（对应契约已删）。跑 `cargo xtask codegen`。",
            orphans.len()
        );
    }
    for o in &orphans {
        std::fs::remove_file(o).with_context(|| format!("删孤儿 {}", o.display()))?;
        eprintln!("  removed orphan {}", o.display());
    }
    Ok(())
}

fn collect_rs_files(dir: &Path, out: &mut Vec<PathBuf>) -> Result<()> {
    if !dir.is_dir() {
        return Ok(());
    }
    for entry in std::fs::read_dir(dir).with_context(|| format!("读目录 {}", dir.display()))? {
        let path = entry?.path();
        if path.is_dir() {
            collect_rs_files(&path, out)?;
        } else if path.extension().and_then(|e| e.to_str()) == Some("rs") {
            out.push(path);
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::atomic::{AtomicU32, Ordering};

    static COUNTER: AtomicU32 = AtomicU32::new(0);

    fn unique_tmp() -> PathBuf {
        let n = COUNTER.fetch_add(1, Ordering::Relaxed);
        std::env::temp_dir().join(format!("rss-xtask-codegen-{}-{n}", std::process::id()))
    }

    /// 在 `root/contracts/http/_seed/v1` 落一个最小 http 契约。
    fn seed_http(root: &Path) -> Result<()> {
        let dir = root.join("contracts/http/_seed/v1");
        std::fs::create_dir_all(&dir)?;
        std::fs::write(
            dir.join("contract.toml"),
            "id = \"seed.echo\"\nkind = \"http\"\ndomain = \"_seed\"\nversion = \"v1\"\nowner = \"_framework\"\nconsistencyLevel = \"LocalOnly\"\nlifecycle = \"draft\"\n[schemas]\nrequest = \"request.schema.json\"\nresponse = \"response.schema.json\"\n",
        )?;
        let schema = "{\"$schema\":\"http://json-schema.org/draft-07/schema#\",\"title\":\"T\",\"type\":\"object\",\"required\":[\"m\"],\"properties\":{\"m\":{\"type\":\"string\"}},\"additionalProperties\":false}";
        std::fs::write(
            dir.join("request.schema.json"),
            schema.replace("\"T\"", "\"SeedEchoRequest\""),
        )?;
        std::fs::write(
            dir.join("response.schema.json"),
            schema.replace("\"T\"", "\"SeedEchoResponse\""),
        )?;
        Ok(())
    }

    #[test]
    fn module_name_joins_domain_version() {
        assert_eq!(module_name("_seed", "v1"), "_seed_v1");
    }

    #[test]
    fn normalize_enforces_single_trailing_newline() {
        assert_eq!(normalize("a\n\n\n"), "a\n");
        assert_eq!(normalize("a"), "a\n");
    }

    #[test]
    fn generate_then_check_is_clean_and_idempotent() -> anyhow::Result<()> {
        let root = unique_tmp();
        seed_http(&root)?;
        let contracts = root.join("contracts");
        let gen_src = root.join("generated/src");
        generate(&contracts, &gen_src, false)?; // 写
        generate(&contracts, &gen_src, true)?; // 校验：无漂移
        let first = std::fs::read_to_string(gen_src.join("http/_seed_v1.rs"))?;
        generate(&contracts, &gen_src, false)?; // 二次生成
        let second = std::fs::read_to_string(gen_src.join("http/_seed_v1.rs"))?;
        let _ = std::fs::remove_dir_all(&root);
        assert_eq!(first, second, "派生须确定性（prettyplease 幂等）");
        assert!(first.contains("SeedEchoRequest") && first.contains("SeedEchoResponse"));
        Ok(())
    }

    #[test]
    fn check_fails_on_injected_drift() -> anyhow::Result<()> {
        // anti-vacuity（负向）：篡改 committed 文件后 --check 必失。
        let root = unique_tmp();
        seed_http(&root)?;
        let contracts = root.join("contracts");
        let gen_src = root.join("generated/src");
        generate(&contracts, &gen_src, false)?;
        std::fs::write(gen_src.join("http/_seed_v1.rs"), "// tampered\n")?;
        let drift = generate(&contracts, &gen_src, true);
        let _ = std::fs::remove_dir_all(&root);
        assert!(drift.is_err(), "漂移须被 --check 抓住");
        Ok(())
    }

    #[test]
    fn check_fails_on_orphan_file() -> anyhow::Result<()> {
        // anti-vacuity（负向）：多出无契约支撑的 .rs 必失。
        let root = unique_tmp();
        seed_http(&root)?;
        let contracts = root.join("contracts");
        let gen_src = root.join("generated/src");
        generate(&contracts, &gen_src, false)?;
        std::fs::write(gen_src.join("http/orphan.rs"), "// stray\n")?;
        let orphan = generate(&contracts, &gen_src, true);
        assert!(orphan.is_err(), "孤儿文件须被 --check 抓住");
        // 写模式删除孤儿后再 check 通过。
        generate(&contracts, &gen_src, false)?;
        let after = generate(&contracts, &gen_src, true);
        let _ = std::fs::remove_dir_all(&root);
        assert!(after.is_ok(), "写模式应已删孤儿");
        Ok(())
    }
}
