//! INVARIANT: ASSEMBLY-GRAPH-CODEGEN-01 { level = "Hard", exec = "check", source = "codegen", golden = "docs/architecture/generated/runtime-assembly.json", synthetic_red = "graph::tests::check_rejects_every_source_mutation_without_writing", anti_vacuity = "graph::tests::committed_runtime_graph_is_non_empty_and_check_clean" } —— JSON/Mermaid 共用闭合 typed model，committed runtime 双产物由字节级 check 守漂移。
//! INVARIANT: ASSEMBLY-GRAPH-SOURCE-CLOSURE-01 { level = "Medium", exec = "check", source = "code", synthetic_red = "graph::tests::check_rejects_every_source_mutation_without_writing", anti_vacuity = "graph::tests::model_and_renderers_are_deterministic_and_non_vacuous" } —— manifest、modules carrier 与 active event subscriptions 必须闭合，门具备非空真实证据与 synthetic red。

use crate::contract::governance::ContractGovernanceIr;
use crate::contract::manifest::{ContractKind, Lifecycle};
use anyhow::{Context, Result, bail};
use serde::Serialize;
use sha2::{Digest, Sha256};
use std::collections::{BTreeMap, BTreeSet};
use std::fs::{self, File, OpenOptions};
use std::io::Write;
use std::path::Path;
use std::sync::atomic::{AtomicU64, Ordering};

const GENERATED_BY: &str = "cargo xtask graph assembly";
#[cfg(test)]
const OWNERSHIP_MARKER_JSON: &str = "\"generatedBy\": \"cargo xtask graph assembly\"";
const OWNERSHIP_MARKER_MERMAID: &str =
    "%% @generated by `cargo xtask graph assembly`; DO NOT EDIT.";
static TEMP_SEQUENCE: AtomicU64 = AtomicU64::new(0);

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum Format {
    Mermaid,
    Json,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct Options {
    assembly: String,
    format: Option<Format>,
    check: bool,
}

impl Default for Options {
    fn default() -> Self {
        Self {
            assembly: "runtime".into(),
            format: None,
            check: false,
        }
    }
}

impl Options {
    pub(crate) fn check_runtime() -> Self {
        Self {
            check: true,
            ..Self::default()
        }
    }
}

pub(crate) fn parse(args: &[&str]) -> Result<Options> {
    let Some((&"assembly", rest)) = args.split_first() else {
        bail!(
            "未知 graph 子命令；用法: cargo xtask graph assembly [--assembly <name>] [--format mermaid|json] [--check]"
        )
    };
    let mut options = Options::default();
    let mut assembly_set = false;
    let mut it = rest.iter();
    while let Some(&arg) = it.next() {
        match arg {
            "--check" if !options.check => options.check = true,
            "--check" => bail!("graph assembly 参数 --check 重复"),
            "--assembly" if !assembly_set => {
                let value = next_value(&mut it, "--assembly")?;
                validate_name(value)?;
                options.assembly = (*value).to_string();
                assembly_set = true;
            }
            "--assembly" => bail!("graph assembly 参数 --assembly 重复"),
            "--format" if options.format.is_none() => {
                options.format = Some(match next_value(&mut it, "--format")? {
                    "mermaid" => Format::Mermaid,
                    "json" => Format::Json,
                    value => bail!("未知 graph format `{value}`；仅支持 mermaid|json"),
                });
            }
            "--format" => bail!("graph assembly 参数 --format 重复"),
            value => bail!("graph assembly 未知参数: {value}"),
        }
    }
    if options.check && options.assembly != "runtime" {
        bail!("--check 仅适用于 committed runtime assembly graph");
    }
    if options.check && options.format.is_some() {
        bail!("--check 必须同时校验 Mermaid/JSON 双产物，禁止与 --format 组合");
    }
    Ok(options)
}

fn next_value<'a>(it: &mut std::slice::Iter<'a, &str>, flag: &str) -> Result<&'a str> {
    let value = *it.next().with_context(|| format!("{flag} 缺值"))?;
    if value.starts_with("--") {
        bail!("{flag} 缺值（收到下一个 flag `{value}`）");
    }
    Ok(value)
}

fn validate_name(name: &str) -> Result<()> {
    if name.is_empty()
        || !name
            .bytes()
            .all(|b| b.is_ascii_lowercase() || b.is_ascii_digit() || b == b'-')
    {
        bail!("assembly name 仅允许非空 lowercase ASCII、数字与连字符");
    }
    Ok(())
}

pub(crate) fn run(options: &Options) -> Result<()> {
    generate_root(&crate::workspace_root()?, options)
}

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
struct GraphModel {
    schema_version: u32,
    generated_by: &'static str,
    assembly: AssemblyMetadata,
    sources: Vec<SourceRecord>,
    nodes: Vec<Node>,
    edges: Vec<Edge>,
}

#[derive(Debug, Clone, Serialize)]
struct SourceRecord {
    path: String,
    digest: SourceDigest,
}
#[derive(Debug, Clone, Serialize)]
struct SourceDigest {
    algorithm: DigestAlgorithm,
    value: String,
}
#[derive(Debug, Clone, Copy, Serialize)]
#[serde(rename_all = "lowercase")]
enum DigestAlgorithm {
    Sha256,
}
#[derive(Debug, Clone, Serialize)]
struct SourceRef {
    path: String,
}

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
struct AssemblyMetadata {
    name: String,
    profile: String,
    topology: String,
}

#[derive(Debug, Clone, Copy, Serialize)]
#[serde(rename_all = "kebab-case")]
enum NodeKind {
    Assembly,
    Domain,
    Provider,
    ListenerSurface,
    Contract,
    Component,
    OutputShape,
    ProbeChannel,
    ResourceChannel,
    WorkerChannel,
}

impl NodeKind {
    fn as_str(self) -> &'static str {
        match self {
            Self::Assembly => "assembly",
            Self::Domain => "domain",
            Self::Provider => "provider",
            Self::ListenerSurface => "listener-surface",
            Self::Contract => "contract",
            Self::Component => "component",
            Self::OutputShape => "output-shape",
            Self::ProbeChannel => "probe-channel",
            Self::ResourceChannel => "resource-channel",
            Self::WorkerChannel => "worker-channel",
        }
    }
}

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
struct Node {
    id: String,
    kind: NodeKind,
    label: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    in_assembly: Option<bool>,
    #[serde(flatten, skip_serializing_if = "Option::is_none")]
    details: Option<NodeDetails>,
}

#[derive(Debug, Clone, Serialize)]
#[serde(untagged)]
enum NodeDetails {
    Provider(ProviderDetails),
    Contract(ContractDetails),
}

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
struct ProviderDetails {
    port: String,
    lifecycle: ProviderLifecycle,
    durability: ProviderDurability,
    #[serde(skip_serializing_if = "Option::is_none")]
    scope: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    failure_posture: Option<String>,
    purpose: String,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    required_features: Vec<String>,
}

#[derive(Debug, Clone, Copy, Serialize)]
#[serde(rename_all = "lowercase")]
enum ProviderLifecycle {
    Draft,
    Active,
    Deprecated,
}

#[derive(Debug, Clone, Copy, Serialize)]
#[serde(rename_all = "kebab-case")]
enum ProviderDurability {
    EphemeralMemory,
    Persistent,
}

#[derive(Debug, Clone, Serialize)]
struct ContractDetails {
    source: SourceRef,
}

#[derive(Debug, Clone, Copy, Serialize)]
#[serde(rename_all = "kebab-case")]
#[derive(PartialEq, Eq)]
enum EdgeKind {
    Contains,
    Exposes,
    BindsListener,
    DeclaresProvider,
    RequiresCapability,
    ContributesOutput,
    DeclaresShape,
    ShapeIncludes,
    Publishes,
    Subscribes,
}

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
struct Edge {
    from: String,
    to: String,
    kind: EdgeKind,
}

struct ModelBuilder {
    nodes: Vec<Node>,
    edges: Vec<Edge>,
    ids: BTreeMap<String, String>,
    keys_by_id: BTreeMap<String, String>,
    domains: BTreeSet<String>,
}

impl ModelBuilder {
    fn new(domains: BTreeSet<String>) -> Self {
        Self {
            nodes: vec![],
            edges: vec![],
            ids: BTreeMap::new(),
            keys_by_id: BTreeMap::new(),
            domains,
        }
    }
    fn node(
        &mut self,
        key: String,
        kind: NodeKind,
        label: String,
        in_assembly: bool,
        details: Option<NodeDetails>,
    ) -> Result<String> {
        if let Some(id) = self.ids.get(&key) {
            return Ok(id.clone());
        }
        if label.chars().any(char::is_control) {
            bail!("graph label 含控制字符");
        }
        let id = canonical_id(&key);
        if let Some(existing) = self.keys_by_id.get(&id)
            && existing != &key
        {
            bail!("graph canonical id collision: {existing} vs {key}");
        }
        self.ids.insert(key.clone(), id.clone());
        self.keys_by_id.insert(id.clone(), key);
        let ownership =
            (matches!(kind, NodeKind::Component) || !in_assembly).then_some(in_assembly);
        self.nodes.push(Node {
            id: id.clone(),
            kind,
            label,
            in_assembly: ownership,
            details,
        });
        Ok(id)
    }
    fn endpoint(&mut self, name: &str) -> Result<String> {
        let inside = self.domains.contains(name);
        self.node(
            format!("endpoint:{name}"),
            if inside {
                NodeKind::Domain
            } else {
                NodeKind::Component
            },
            name.to_string(),
            inside,
            None,
        )
    }
    fn edge(&mut self, from: &str, to: &str, kind: EdgeKind) {
        self.edges.push(Edge {
            from: from.into(),
            to: to.into(),
            kind,
        });
    }
}

fn build_model(root: &Path, assembly_name: &str) -> Result<GraphModel> {
    validate_name(assembly_name)?;
    let ir = crate::assembly_governance::AssemblyGovernanceIr::<
        crate::assembly_governance::Core,
    >::load_target(root, assembly_name)?
    .with_context(|| format!("assembly `{assembly_name}` is not governed"))?;
    let assembly = ir
        .assembly(assembly_name)
        .with_context(|| format!("assembly `{assembly_name}` is not governed"))?;
    let manifest = assembly.manifest();
    crate::assembly_codegen::check_governed_target(root, assembly)
        .context("modules_gen carrier 与 manifest 漂移")?;
    if root.join("Cargo.toml").is_file() {
        let assembly_findings = crate::assembly::validate_governed_target(root, assembly)?;
        reject_findings("assembly graph target validation", &assembly_findings)?;
    }
    let (_, findings) = crate::contract::validate::validate_root(&root.join("contracts"))?;
    reject_findings("assembly graph contract source validation", &findings)?;

    let domains: BTreeSet<_> = manifest
        .domains()
        .iter()
        .map(|d| d.as_str().to_string())
        .collect();
    let mut builder = ModelBuilder::new(domains.clone());
    let assembly_id = builder.node(
        format!("assembly:{assembly_name}"),
        NodeKind::Assembly,
        assembly_name.into(),
        true,
        None,
    )?;
    for domain in manifest.domains() {
        let id = builder.endpoint(domain.as_str())?;
        builder.edge(&assembly_id, &id, EdgeKind::Contains);
    }
    for listener in manifest.listeners() {
        let id = builder.node(
            format!("listener:{}", listener.kind.as_str()),
            NodeKind::ListenerSurface,
            format!("{} listener surface", listener.kind.as_str()),
            true,
            None,
        )?;
        builder.edge(&assembly_id, &id, EdgeKind::Exposes);
        for domain in &listener.domains {
            let domain_id = builder.endpoint(domain.as_str())?;
            builder.edge(&domain_id, &id, EdgeKind::BindsListener);
        }
    }
    let output = builder.node(
        "runtime-output".into(),
        NodeKind::OutputShape,
        "DomainModuleResult declared shape".into(),
        true,
        None,
    )?;
    let resources = builder.node(
        "resources-channel".into(),
        NodeKind::ResourceChannel,
        "resources channel".into(),
        true,
        None,
    )?;
    let workers = builder.node(
        "workers-channel".into(),
        NodeKind::WorkerChannel,
        "workers channel".into(),
        true,
        None,
    )?;
    let probes = builder.node(
        "probes-channel".into(),
        NodeKind::ProbeChannel,
        "probes channel".into(),
        true,
        None,
    )?;
    builder.edge(&assembly_id, &output, EdgeKind::DeclaresShape);
    for channel in [&probes, &resources, &workers] {
        builder.edge(&output, channel, EdgeKind::ShapeIncludes);
    }
    for provider in manifest.declaration_ordered_diport_providers() {
        let consumer_name = provider.consumer.as_str();
        let details = ProviderDetails {
            port: provider.port.as_str().into(),
            lifecycle: provider_lifecycle(provider.lifecycle),
            durability: provider_durability(provider.durability),
            scope: provider.scope.map(|scope| scope.to_string()),
            failure_posture: provider.failure_posture.map(|posture| posture.to_string()),
            purpose: provider.purpose.clone(),
            required_features: provider.required_features.clone(),
        };
        let id = builder.node(
            format!(
                "provider:{}:{}:{}",
                provider.port.as_str(),
                provider.provider,
                consumer_name
            ),
            NodeKind::Provider,
            format!("{} ({})", provider.provider, provider.provider_crate),
            true,
            Some(NodeDetails::Provider(details)),
        )?;
        let consumer = if consumer_name == manifest.name() {
            assembly_id.clone()
        } else if domains.contains(consumer_name) {
            builder.endpoint(consumer_name)?
        } else {
            builder.node(
                format!("endpoint:{consumer_name}"),
                NodeKind::Component,
                consumer_name.to_owned(),
                true,
                None,
            )?
        };
        builder.edge(&consumer, &id, EdgeKind::RequiresCapability);
        builder.edge(&assembly_id, &id, EdgeKind::DeclaresProvider);
        for channel in &provider.outputs {
            let channel_id = match channel {
                assembly_schema::LifecycleChannel::Probes => &probes,
                assembly_schema::LifecycleChannel::Resources => &resources,
                assembly_schema::LifecycleChannel::Workers => &workers,
            };
            builder.edge(&id, channel_id, EdgeKind::ContributesOutput);
        }
    }

    let modules_path = root.join(format!(
        "assemblies/{assembly_name}/src/generated/modules_gen.rs"
    ));
    let mut sources = vec![
        source_record_content(assembly.source_label(), assembly.source_text().as_bytes()),
        source_record(root, &modules_path)?,
    ];
    let contract_governance = ContractGovernanceIr::load_consumer_workspace(root)?;
    contract_governance.read(|contracts| {
        for contract in contracts {
            let m = contract.manifest();
            if m.kind != ContractKind::Event || m.lifecycle != Lifecycle::Active {
                continue;
            }
            let relevant = domains.contains(&m.domain)
                || m.subscriptions
                    .iter()
                    .any(|s| domains.contains(&s.consumer));
            if !relevant {
                continue;
            }
            let source_path = contract.manifest_path();
            let source = relative(root, source_path)?;
            sources.push(source_record_content(&source, contract.manifest_bytes()));
            let contract_id = builder.node(
                format!("contract:{}", m.id),
                NodeKind::Contract,
                m.id.clone(),
                domains.contains(&m.domain),
                Some(NodeDetails::Contract(ContractDetails {
                    source: SourceRef { path: source },
                })),
            )?;
            let producer = builder.endpoint(&m.domain)?;
            builder.edge(&producer, &contract_id, EdgeKind::Publishes);
            for sub in &m.subscriptions {
                let consumer = builder.endpoint(&sub.consumer)?;
                builder.edge(&contract_id, &consumer, EdgeKind::Subscribes);
            }
        }
        Ok(())
    })?;
    sources.push(source_record(
        root,
        &root.join("crates/bootstrap/src/module.rs"),
    )?);
    sources.sort_by(|left, right| left.path.cmp(&right.path));
    sources.dedup_by(|left, right| left.path == right.path);
    validate_model(&builder.nodes, &builder.edges)?;
    Ok(GraphModel {
        schema_version: 1,
        generated_by: GENERATED_BY,
        assembly: AssemblyMetadata {
            name: manifest.name().to_owned(),
            profile: manifest.profile().as_str().into(),
            topology: manifest.topology().as_str().into(),
        },
        sources,
        nodes: builder.nodes,
        edges: builder.edges,
    })
}

fn validate_model(nodes: &[Node], edges: &[Edge]) -> Result<()> {
    let ids: BTreeSet<_> = nodes.iter().map(|n| n.id.as_str()).collect();
    if ids.len() != nodes.len() {
        bail!("graph node id 重复");
    }
    if edges
        .iter()
        .any(|e| !ids.contains(e.from.as_str()) || !ids.contains(e.to.as_str()))
    {
        bail!("graph 包含悬空 edge");
    }
    Ok(())
}

fn render_json(model: &GraphModel) -> Result<String> {
    Ok(format!("{}\n", serde_json::to_string_pretty(model)?))
}

fn render_mermaid(model: &GraphModel) -> Result<String> {
    let mut out = format!("{OWNERSHIP_MARKER_MERMAID}\nflowchart LR\n");
    for source in &model.sources {
        out.push_str(&format!(
            "  %% Source: {} (sha256:{})\n",
            source.path, source.digest.value
        ));
    }
    for node in &model.nodes {
        out.push_str(&format!(
            "  {}[\"{}\"]\n",
            node.id,
            escape_mermaid(&mermaid_node_label(node))
        ));
    }
    for edge in &model.edges {
        out.push_str(&format!(
            "  {} -->|{}| {}\n",
            edge.from,
            edge_label(edge.kind),
            edge.to
        ));
    }
    Ok(out)
}

fn mermaid_node_label(node: &Node) -> String {
    let ownership = if node.in_assembly == Some(false) {
        " external"
    } else {
        ""
    };
    let provider = match &node.details {
        Some(NodeDetails::Provider(details)) => {
            let scope = details
                .scope
                .as_deref()
                .map_or(String::new(), |scope| format!(" {scope}"));
            let posture = details
                .failure_posture
                .as_deref()
                .map_or(String::new(), |posture| format!(" {posture}"));
            format!(
                " {} {}{scope}{posture}",
                provider_lifecycle_label(details.lifecycle),
                provider_durability_label(details.durability)
            )
        }
        _ => String::new(),
    };
    format!(
        "[{}{}{}] {}",
        node.kind.as_str(),
        ownership,
        provider,
        node.label
    )
}

fn canonical_id(key: &str) -> String {
    let digest = Sha256::digest(key.as_bytes());
    let mut id = String::from("n_");
    for byte in &digest[..12] {
        id.push_str(&format!("{byte:02x}"));
    }
    id
}

fn source_record(root: &Path, path: &Path) -> Result<SourceRecord> {
    ensure_no_symlinks(root, path)?;
    let bytes = fs::read(path).with_context(|| format!("读取 graph source {}", path.display()))?;
    Ok(source_record_content(&relative(root, path)?, &bytes))
}

fn source_record_content(path: &str, bytes: &[u8]) -> SourceRecord {
    let digest = Sha256::digest(bytes);
    let mut value = String::new();
    for byte in digest {
        value.push_str(&format!("{byte:02x}"));
    }
    SourceRecord {
        path: path.to_owned(),
        digest: SourceDigest {
            algorithm: DigestAlgorithm::Sha256,
            value,
        },
    }
}

fn reject_findings<R: std::fmt::Debug>(
    context: &str,
    findings: &[crate::diagnostic::Finding<R>],
) -> Result<()> {
    if findings.is_empty() {
        return Ok(());
    }
    crate::diagnostic::print_findings(findings);
    bail!("{context}: {} 项校验失败", findings.len())
}

fn provider_lifecycle(value: assembly_schema::ProviderLifecycle) -> ProviderLifecycle {
    match value {
        assembly_schema::ProviderLifecycle::Draft => ProviderLifecycle::Draft,
        assembly_schema::ProviderLifecycle::Active => ProviderLifecycle::Active,
        assembly_schema::ProviderLifecycle::Deprecated => ProviderLifecycle::Deprecated,
    }
}
fn provider_durability(value: assembly_schema::ProviderDurability) -> ProviderDurability {
    match value {
        assembly_schema::ProviderDurability::EphemeralMemory => ProviderDurability::EphemeralMemory,
        assembly_schema::ProviderDurability::Persistent => ProviderDurability::Persistent,
    }
}
fn provider_lifecycle_label(value: ProviderLifecycle) -> &'static str {
    match value {
        ProviderLifecycle::Draft => "draft",
        ProviderLifecycle::Active => "active",
        ProviderLifecycle::Deprecated => "deprecated",
    }
}
fn provider_durability_label(value: ProviderDurability) -> &'static str {
    match value {
        ProviderDurability::EphemeralMemory => "ephemeral-memory",
        ProviderDurability::Persistent => "persistent",
    }
}

fn edge_label(kind: EdgeKind) -> &'static str {
    match kind {
        EdgeKind::Contains => "contains",
        EdgeKind::Exposes => "exposes",
        EdgeKind::BindsListener => "binds listener",
        EdgeKind::DeclaresProvider => "declares provider",
        EdgeKind::RequiresCapability => "requires capability",
        EdgeKind::ContributesOutput => "contributes output",
        EdgeKind::DeclaresShape => "declares output shape",
        EdgeKind::ShapeIncludes => "declared shape includes",
        EdgeKind::Publishes => "publishes",
        EdgeKind::Subscribes => "subscribes",
    }
}
fn escape_mermaid(value: &str) -> String {
    value
        .replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
}

fn generate_root(root: &Path, options: &Options) -> Result<()> {
    let model = build_model(root, &options.assembly)?;
    let base = if options.assembly == "runtime" {
        root.join("docs/architecture/generated/runtime-assembly")
    } else {
        root.join("target/xtask")
            .join(format!("{}-assembly", options.assembly))
    };
    let formats: &[Format] = match options.format {
        Some(Format::Json) => &[Format::Json],
        Some(Format::Mermaid) => &[Format::Mermaid],
        None => &[Format::Mermaid, Format::Json],
    };
    let mut targets = Vec::new();
    for format in formats {
        let (path, content) = match format {
            Format::Json => (base.with_extension("json"), render_json(&model)?),
            Format::Mermaid => (base.with_extension("mmd"), render_mermaid(&model)?),
        };
        ensure_no_symlinks(root, &path)?;
        let actual = if options.check || path.exists() {
            let actual = fs::read_to_string(&path).with_context(|| {
                format!(
                    "缺少 committed graph {}",
                    relative(root, &path).unwrap_or_else(|_| path.display().to_string())
                )
            })?;
            ensure_owned(&path, &actual, *format)?;
            Some(actual)
        } else {
            None
        };
        targets.push((path, content, actual));
    }
    if options.check {
        for (path, content, actual) in &targets {
            let actual = actual
                .as_deref()
                .context("check target missing after planning")?;
            if actual != content {
                bail!(
                    "assembly graph 派生漂移: {}；运行 `cargo xtask graph assembly`",
                    relative(root, path)?
                );
            }
        }
        eprintln!("graph assembly --check: 无漂移");
        return Ok(());
    }
    for (path, content, actual) in targets {
        if actual.as_deref() != Some(content.as_str()) {
            atomic_write(&path, content.as_bytes())?;
            eprintln!("generated {}", relative(root, &path)?);
        }
    }
    Ok(())
}

fn ensure_owned(path: &Path, content: &str, format: Format) -> Result<()> {
    let owned = match format {
        Format::Mermaid => content.starts_with(OWNERSHIP_MARKER_MERMAID),
        Format::Json => serde_json::from_str::<serde_json::Value>(content)
            .ok()
            .and_then(|v| {
                v.get("generatedBy")
                    .and_then(|v| v.as_str())
                    .map(|v| v == GENERATED_BY)
            })
            .unwrap_or(false),
    };
    if !owned {
        bail!("拒绝覆盖或检查非本生成器文件：{}", path.display());
    }
    Ok(())
}

fn reject_symlink(path: &Path) -> Result<()> {
    if fs::symlink_metadata(path).is_ok_and(|m| m.file_type().is_symlink()) {
        bail!("graph 路径禁止符号链接：{}", path.display());
    }
    Ok(())
}
fn ensure_no_symlinks(root: &Path, path: &Path) -> Result<()> {
    let rel = path
        .strip_prefix(root)
        .context("graph 输出越过 workspace")?;
    let mut current = root.to_path_buf();
    for c in rel.components() {
        current.push(c);
        reject_symlink(&current)?;
    }
    Ok(())
}
fn relative(root: &Path, path: &Path) -> Result<String> {
    Ok(path
        .strip_prefix(root)
        .context("source 越过 workspace")?
        .components()
        .map(|c| c.as_os_str().to_string_lossy())
        .collect::<Vec<_>>()
        .join("/"))
}

fn atomic_write(path: &Path, content: &[u8]) -> Result<()> {
    let parent = path.parent().context("graph target 无父目录")?;
    fs::create_dir_all(parent)?;
    let tmp = parent.join(format!(
        ".graph.tmp-{}-{}",
        std::process::id(),
        TEMP_SEQUENCE.fetch_add(1, Ordering::Relaxed)
    ));
    let result = (|| -> Result<()> {
        let mut f = OpenOptions::new().create_new(true).write(true).open(&tmp)?;
        f.write_all(content)?;
        f.sync_all()?;
        drop(f);
        fs::rename(&tmp, path)?;
        File::open(parent)?.sync_all()?;
        Ok(())
    })();
    if result.is_err() {
        let _ = fs::remove_file(&tmp);
    }
    result
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn cli_is_closed_and_defaults_to_runtime_both_formats() -> anyhow::Result<()> {
        assert_eq!(parse(&["assembly"])?, Options::default());
        assert!(parse(&["assembly", "--check"])?.check);
        assert_eq!(
            parse(&["assembly", "--format", "json"])?.format,
            Some(Format::Json)
        );
        assert!(parse(&["assembly", "--assembly", "settingsonly", "--check"]).is_err());
        assert!(parse(&["assembly", "--check", "--format", "json"]).is_err());
        assert!(parse(&["assembly", "--format", "mermaid", "--check"]).is_err());
        assert!(parse(&["assembly", "--format", "yaml"]).is_err());
        assert!(parse(&["assembly", "--format", "json", "--format", "mermaid"]).is_err());
        for args in [
            &["assembly", "--assembly", "--check"][..],
            &["assembly", "--format", "--check"][..],
        ] {
            let error = parse(args)
                .err()
                .context("missing flag value unexpectedly accepted")?;
            assert!(error.to_string().contains("缺值"), "{error}");
        }
        Ok(())
    }

    #[test]
    #[allow(clippy::cognitive_complexity)] // reason: anti-vacuity test validates both renderers and every typed graph edge family together.
    fn model_and_renderers_are_deterministic_and_non_vacuous() -> anyhow::Result<()> {
        let root = fixture_root("assembly-graph-green")?;
        write_fixture(&root)?;
        crate::assembly_codegen::generate_root(&root, false)?;
        let model = build_model(&root, "runtime")?;
        assert!(!model.nodes.is_empty() && !model.edges.is_empty());
        let json = render_json(&model)?;
        let mermaid = render_mermaid(&model)?;
        assert_eq!(json, render_json(&build_model(&root, "runtime")?)?);
        assert!(json.contains("\"inAssembly\": false"));
        assert!(mermaid.contains("[provider active ephemeral-memory]"));
        assert!(mermaid.contains("[component external] outside"));
        assert!(mermaid.contains("Source: contracts/event/identity/v1/created/contract.toml"));
        assert!(!json.contains(root.to_string_lossy().as_ref()));
        let provider = model
            .nodes
            .iter()
            .find(|node| node.label.contains("GovernorLimiter"))
            .context("fixture provider missing")?;
        let consumer = model
            .nodes
            .iter()
            .find(|node| node.label == "httpserve")
            .context("provider consumer missing")?;
        assert_eq!(consumer.in_assembly, Some(true));
        let outside = model
            .nodes
            .iter()
            .find(|node| node.label == "outside")
            .context("outside subscriber missing")?;
        assert_eq!(outside.in_assembly, Some(false));
        assert!(model.edges.iter().any(|edge| edge.from == consumer.id
            && edge.to == provider.id
            && edge.kind == EdgeKind::RequiresCapability));
        let assembly = model
            .nodes
            .iter()
            .find(|node| matches!(node.kind, NodeKind::Assembly))
            .context("assembly missing")?;
        let domain = model
            .nodes
            .iter()
            .find(|node| node.label == "identity")
            .context("domain missing")?;
        assert!(model.edges.iter().any(|edge| edge.from == assembly.id
            && edge.to == domain.id
            && edge.kind == EdgeKind::Contains));
        assert!(model.edges.iter().any(|edge| edge.from == assembly.id
            && edge.to == provider.id
            && edge.kind == EdgeKind::DeclaresProvider));
        let listener = model
            .nodes
            .iter()
            .find(|node| node.label == "primary listener surface")
            .context("listener missing")?;
        assert!(model.edges.iter().any(|edge| edge.from == domain.id
            && edge.to == listener.id
            && edge.kind == EdgeKind::BindsListener));
        let resources = model
            .nodes
            .iter()
            .find(|node| node.label == "resources channel")
            .context("resources channel missing")?;
        assert!(
            !model
                .edges
                .iter()
                .any(|edge| edge.from == provider.id && edge.kind == EdgeKind::ContributesOutput),
            "active provider with outputs=[] must not gain a lifecycle edge"
        );
        let signer = model
            .nodes
            .iter()
            .find(|node| node.label.contains("VaultSigner"))
            .context("resource-contributing provider missing")?;
        assert!(model.edges.iter().any(|edge| edge.from == signer.id
            && edge.to == resources.id
            && edge.kind == EdgeKind::ContributesOutput));
        assert!(!render_json(&model)?.contains("produces"));
        assert_declared_shape(&model)?;
        let value: serde_json::Value = serde_json::from_str(&json)?;
        assert_eq!(value["sources"][0]["digest"]["algorithm"], "sha256");
        std::fs::remove_dir_all(root)?;
        Ok(())
    }

    #[test]
    fn canonical_ids_are_stable_when_an_earlier_node_is_inserted() -> anyhow::Result<()> {
        let mut first = ModelBuilder::new(BTreeSet::new());
        let stable = first.node(
            "stable".into(),
            NodeKind::Component,
            "stable".into(),
            true,
            None,
        )?;
        let mut second = ModelBuilder::new(BTreeSet::new());
        second.node(
            "earlier".into(),
            NodeKind::Component,
            "earlier".into(),
            true,
            None,
        )?;
        let after_insert = second.node(
            "stable".into(),
            NodeKind::Component,
            "stable".into(),
            true,
            None,
        )?;
        assert_eq!(stable, after_insert);
        Ok(())
    }

    #[test]
    fn check_rejects_every_source_mutation_without_writing() -> anyhow::Result<()> {
        for mutation in [
            "listener",
            "listener-binding",
            "provider",
            "provider-output",
            "contract",
            "subscription",
            "shape",
        ] {
            let root = fixture_root(&format!("assembly-graph-drift-{mutation}"))?;
            write_fixture(&root)?;
            crate::assembly_codegen::generate_root(&root, false)?;
            generate_root(&root, &Options::default())?;
            let json = root.join("docs/architecture/generated/runtime-assembly.json");
            let mermaid = root.join("docs/architecture/generated/runtime-assembly.mmd");
            let before_json = std::fs::read(&json)?;
            let before_mermaid = std::fs::read(&mermaid)?;
            let (path, from, to) = match mutation {
                "listener" => (
                    root.join("assemblies/runtime/assembly.toml"),
                    "kind = \"primary\"",
                    "kind = \"health\"",
                ),
                "listener-binding" => (
                    root.join("assemblies/runtime/assembly.toml"),
                    "domains = [\"identity\"]",
                    "domains = []",
                ),
                "provider" => (
                    root.join("assemblies/runtime/assembly.toml"),
                    "purpose = \"test\"",
                    "purpose = \"changed\"",
                ),
                "provider-output" => (
                    root.join("assemblies/runtime/assembly.toml"),
                    "outputs = [\"resources\"]",
                    "outputs = []",
                ),
                "contract" => (
                    root.join("contracts/event/identity/v1/created/contract.toml"),
                    "topic = \"identity.created\"",
                    "topic = \"identity.changed\"",
                ),
                "subscription" => (
                    root.join("contracts/event/identity/v1/created/contract.toml"),
                    "group = \"outside.created\"",
                    "group = \"outside.changed\"",
                ),
                "shape" => (
                    root.join("crates/bootstrap/src/module.rs"),
                    "workers: ()",
                    "workers: usize",
                ),
                _ => unreachable!(),
            };
            let content = std::fs::read_to_string(&path)?.replace(from, to);
            std::fs::write(path, content)?;
            assert!(
                generate_root(&root, &Options::check_runtime()).is_err(),
                "{mutation} drift accepted"
            );
            assert_eq!(std::fs::read(&json)?, before_json);
            assert_eq!(std::fs::read(&mermaid)?, before_mermaid);
            std::fs::remove_dir_all(root)?;
        }
        let root = fixture_root("assembly-graph-output-tamper")?;
        write_fixture(&root)?;
        crate::assembly_codegen::generate_root(&root, false)?;
        generate_root(&root, &Options::default())?;
        let json = root.join("docs/architecture/generated/runtime-assembly.json");
        let mermaid = root.join("docs/architecture/generated/runtime-assembly.mmd");
        let original_json = std::fs::read(&json)?;
        std::fs::write(&json, format!("{OWNERSHIP_MARKER_JSON}\n{{}}\n"))?;
        let tampered = std::fs::read(&json)?;
        assert!(generate_root(&root, &Options::check_runtime()).is_err());
        assert_eq!(std::fs::read(&json)?, tampered);
        std::fs::write(&json, original_json)?;
        std::fs::write(&mermaid, format!("{OWNERSHIP_MARKER_MERMAID}\nbroken\n"))?;
        let tampered = std::fs::read(&mermaid)?;
        assert!(generate_root(&root, &Options::check_runtime()).is_err());
        assert_eq!(std::fs::read(&mermaid)?, tampered);
        std::fs::remove_dir_all(root)?;
        Ok(())
    }

    #[test]
    fn duplicate_contract_id_fails_before_graph_consumes_sources() -> anyhow::Result<()> {
        let root = fixture_root("assembly-graph-duplicate-contract")?;
        write_fixture(&root)?;
        crate::assembly_codegen::generate_root(&root, false)?;
        let duplicate = root.join("contracts/event/identity/v1/duplicate");
        std::fs::create_dir_all(&duplicate)?;
        std::fs::copy(
            root.join("contracts/event/identity/v1/created/contract.toml"),
            duplicate.join("contract.toml"),
        )?;
        std::fs::copy(
            root.join("contracts/event/identity/v1/created/payload.schema.json"),
            duplicate.join("payload.schema.json"),
        )?;
        let error = match build_model(&root, "runtime") {
            Ok(_) => bail!("duplicate contract id unexpectedly accepted"),
            Err(error) => error,
        };
        let diagnostic = format!("{error:#}");
        assert!(
            diagnostic.contains("contract governance rejected")
                && diagnostic.contains("[R12]")
                && diagnostic.contains("identity.created"),
            "{diagnostic}"
        );
        std::fs::remove_dir_all(root)?;
        Ok(())
    }

    #[test]
    fn target_validation_rejects_durability_and_required_capability() -> anyhow::Result<()> {
        for (name, from, to) in [
            (
                "durability",
                "durability = \"persistent\"",
                "durability = \"ephemeral-memory\"",
            ),
            (
                "capability",
                "lifecycle = \"active\"",
                "lifecycle = \"draft\"",
            ),
        ] {
            let root = fixture_root(&format!("assembly-graph-target-{name}"))?;
            write_fixture(&root)?;
            let path = root.join("assemblies/runtime/assembly.toml");
            let original = std::fs::read_to_string(&path)?;
            let changed = if name == "capability" {
                original.replace(from, to)
            } else {
                original.replacen(from, to, 1)
            };
            std::fs::write(&path, changed)?;
            let error = match crate::assembly_codegen::generate_root(&root, false) {
                Ok(()) => build_model(&root, "runtime")
                    .err()
                    .context("invalid target accepted")?,
                Err(error) => error,
            };
            let diagnostic = format!("{error:#}");
            assert!(
                diagnostic.contains("invalid assembly declarations")
                    || diagnostic.contains("项校验失败"),
                "{diagnostic}"
            );
            std::fs::remove_dir_all(root)?;
        }
        Ok(())
    }

    #[test]
    fn target_graph_does_not_load_unrelated_assembly_sources() -> anyhow::Result<()> {
        let root = fixture_root("assembly-graph-target-scope")?;
        write_fixture(&root)?;
        crate::assembly_codegen::generate_root(&root, false)?;
        std::fs::write(
            root.join("assemblies/identityaudit/assembly.toml"),
            "unrelated invalid manifest = [",
        )?;
        build_model(&root, "runtime")?;
        std::fs::remove_dir_all(root)?;
        Ok(())
    }

    #[test]
    fn non_launch_assembly_only_declares_output_shape() -> anyhow::Result<()> {
        let root = fixture_root("assembly-graph-non-launch")?;
        write_fixture(&root)?;
        crate::assembly_codegen::generate_root(&root, false)?;
        let rendered = render_mermaid(&build_model(&root, "settingsonly")?)?;
        assert!(!rendered.contains("produces") && !rendered.contains(" live"));
        assert!(rendered.contains("declares output shape"));
        std::fs::remove_dir_all(root)?;
        Ok(())
    }

    #[cfg(unix)]
    #[test]
    fn output_symlink_is_rejected_without_touching_target() -> anyhow::Result<()> {
        use std::os::unix::fs::symlink;
        let root = fixture_root("assembly-graph-symlink")?;
        write_fixture(&root)?;
        crate::assembly_codegen::generate_root(&root, false)?;
        let outside = crate::testutil::unique_tmp("assembly-graph-outside");
        std::fs::create_dir_all(&outside)?;
        std::fs::create_dir_all(root.join("docs/architecture"))?;
        symlink(&outside, root.join("docs/architecture/generated"))?;
        assert!(generate_root(&root, &Options::default()).is_err());
        assert!(!outside.join("runtime-assembly.json").exists());
        std::fs::remove_file(root.join("docs/architecture/generated"))?;
        std::fs::remove_dir_all(root)?;
        std::fs::remove_dir_all(outside)?;
        Ok(())
    }

    #[cfg(unix)]
    #[test]
    fn manifest_parent_symlink_is_rejected_before_read() -> anyhow::Result<()> {
        use std::os::unix::fs::symlink;
        let root = crate::testutil::unique_tmp("assembly-graph-source-symlink");
        let outside = crate::testutil::unique_tmp("assembly-graph-source-outside");
        std::fs::create_dir_all(&root)?;
        std::fs::create_dir_all(outside.join("runtime"))?;
        std::fs::write(
            outside.join("runtime/assembly.toml"),
            manifest("identity", "primary"),
        )?;
        symlink(&outside, root.join("assemblies"))?;
        assert!(build_model(&root, "runtime").is_err());
        std::fs::remove_file(root.join("assemblies"))?;
        std::fs::remove_dir_all(root)?;
        std::fs::remove_dir_all(outside)?;
        Ok(())
    }

    #[test]
    fn committed_runtime_graph_is_non_empty_and_check_clean() -> anyhow::Result<()> {
        let root = crate::workspace_root()?;
        let model = build_model(&root, "runtime")?;
        assert!(!model.nodes.is_empty() && !model.edges.is_empty());
        let assembly = model
            .nodes
            .iter()
            .find(|node| matches!(node.kind, NodeKind::Assembly))
            .context("runtime assembly node missing")?;
        let self_provider = model
            .nodes
            .iter()
            .find(|node| node.label.contains("S3Store"))
            .context("runtime self provider missing")?;
        assert!(model.edges.iter().any(|edge| edge.from == assembly.id
            && edge.to == self_provider.id
            && edge.kind == EdgeKind::RequiresCapability));
        let httpserve = model
            .nodes
            .iter()
            .find(|node| node.label == "httpserve")
            .context("httpserve component missing")?;
        assert_eq!(httpserve.in_assembly, Some(true));
        generate_root(&root, &Options::check_runtime())
    }

    fn fixture_root(name: &str) -> anyhow::Result<std::path::PathBuf> {
        let root = crate::testutil::unique_tmp(name);
        let workspace = crate::workspace_root()?;
        for name in ["identityaudit", "runtime", "settingsonly"] {
            let target = root.join("assemblies").join(name);
            std::fs::create_dir_all(&target)?;
            std::fs::copy(
                workspace.join("assemblies").join(name).join("Cargo.toml"),
                target.join("Cargo.toml"),
            )?;
            if name != "runtime" {
                std::fs::copy(
                    workspace
                        .join("assemblies")
                        .join(name)
                        .join("assembly.toml"),
                    target.join("assembly.toml"),
                )?;
            }
        }
        let relay = root.join("assemblies/runtime/src/event_transport.rs");
        std::fs::create_dir_all(relay.parent().context("runtime relay parent")?)?;
        std::fs::copy(
            workspace.join("assemblies/runtime/src/event_transport.rs"),
            relay,
        )?;
        copy_tree(&workspace.join("contracts"), &root.join("contracts"))?;
        std::fs::create_dir_all(root.join("contracts/event/identity/v1/created"))?;
        Ok(std::fs::canonicalize(root)?)
    }

    fn copy_tree(source: &Path, target: &Path) -> anyhow::Result<()> {
        std::fs::create_dir_all(target)?;
        for entry in std::fs::read_dir(source)? {
            let entry = entry?;
            let source_path = entry.path();
            let target_path = target.join(entry.file_name());
            if entry.file_type()?.is_dir() {
                copy_tree(&source_path, &target_path)?;
            } else {
                std::fs::copy(source_path, target_path)?;
            }
        }
        Ok(())
    }

    fn assert_declared_shape(model: &GraphModel) -> anyhow::Result<()> {
        let shape = model
            .nodes
            .iter()
            .find(|node| node.label == "DomainModuleResult declared shape")
            .context("declared shape missing")?;
        for label in ["probes channel", "resources channel", "workers channel"] {
            let channel = model
                .nodes
                .iter()
                .find(|node| node.label == label)
                .context("declared channel missing")?;
            assert!(model.edges.iter().any(|edge| edge.from == shape.id
                && edge.to == channel.id
                && edge.kind == EdgeKind::ShapeIncludes));
        }
        Ok(())
    }

    fn manifest(domain: &str, listener: &str) -> String {
        manifest_named("runtime", domain, listener, "httpserve")
    }

    fn manifest_named(name: &str, domain: &str, listener: &str, consumer: &str) -> String {
        format!(
            r#"schemaVersion = 2
name = "{name}"
profile = "demo"
domains = ["{domain}"]
topology = "demo"
frameworkContracts = []
workflowActivations = []
[[listeners]]
kind = "{listener}"
domains = ["{domain}"]
[[diportProviders]]
id = "listener-rate-limiter"
port = "diport::RateLimiter"
provider = "ratelimit::GovernorLimiter"
providerCrate = "ratelimit"
consumer = "{consumer}"
lifecycle = "active"
durability = "ephemeral-memory"
purpose = "test"
outputs = []

[[diportProviders]]
id = "identity-signer"
port = "diport::Signer"
provider = "vault::VaultSigner"
providerCrate = "vault"
requiredFeatures = ["backend"]
consumer = "identity"
lifecycle = "active"
durability = "persistent"
purpose = "identity-signing"
outputs = ["probes", "resources", "workers"]

[[diportProviders]]
id = "listener-pdp"
port = "diport::Pdp"
provider = "oidc::OidcProvider"
providerCrate = "oidc"
requiredFeatures = ["backend"]
consumer = "httpserve"
lifecycle = "active"
durability = "persistent"
purpose = "identity-auth"
outputs = ["resources"]

[[diportProviders]]
id = "service-token-replay-store"
port = "diport::ServiceTokenReplayStore"
provider = "postgres::PgServiceTokenReplayStore"
providerCrate = "postgres"
consumer = "oidc"
lifecycle = "active"
durability = "persistent"
scope = "cluster-global"
failurePosture = "fail-closed"
purpose = "service-token-atomic-replay-consume"
outputs = ["probes", "resources", "workers"]
"#
        )
    }

    fn write_fixture(root: &std::path::Path) -> anyhow::Result<()> {
        std::fs::create_dir_all(root.join("crates/bootstrap/src"))?;
        std::fs::write(
            root.join("crates/bootstrap/src/module.rs"),
            "pub struct DomainModuleResult { probes: (), resources: (), workers: () }\n",
        )?;
        std::fs::write(
            root.join("assemblies/runtime/Cargo.toml"),
            r#"[package]
name="runtime"
version="0.0.0"
edition="2024"
[dependencies]
identity={path="../../../identity"}
ratelimit={path="../../../ratelimit"}
postgres={path="../../../postgres",features=["domain-identity"]}
vault={path="../../../vault",features=["backend"]}
oidc={path="../../../oidc",features=["backend"]}
"#,
        )?;
        std::fs::write(
            root.join("assemblies/runtime/assembly.toml"),
            manifest("identity", "primary"),
        )?;
        std::fs::write(
            root.join("contracts/event/identity/v1/created/contract.toml"),
            r#"id = "identity.created"
kind = "event"
domain = "identity"
version = "v1"
owner = "identity"
consistencyLevel = "OutboxFact"
lifecycle = "active"
topic = "identity.created"
delivery = "at-least-once"
[schemas]
payload = "payload.schema.json"
[capabilities.outbox]
role = "fact"
[[subscriptions]]
consumer = "outside"
group = "outside.created"
execution = "adapter-native"
externalEffectPolicy = "transactional-only"
[subscriptions.topology]
partitionKey = "none"
readiness = "required"
"#,
        )?;
        std::fs::write(
            root.join("contracts/event/identity/v1/created/payload.schema.json"),
            r#"{"$schema":"http://json-schema.org/draft-07/schema#","title":"IdentityCreatedPayload","type":"object","additionalProperties":false}"#,
        )?;
        Ok(())
    }
}
