[package]
name = "s3-integration"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dev-dependencies]
aws-sdk-s3 = { workspace = true }
diport = { path = "../../crates/diport" }
eventexec = { path = "../../crates/eventexec" }
s3 = { path = "../../adapters/s3", features = ["integration"] }
secure = { path = "../../crates/secure" }
testkit = { path = "../../crates/testkit", features = ["containers"] }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
uuid = { workspace = true, features = ["v4"] }

[lints]
workspace = true
