[package]
name = "server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[lints]
workspace = true

[[bin]]
name = "server"
path = "src/main.rs"

[dependencies]
runtime = { path = "../../assemblies/runtime" }
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
anyhow = { workspace = true }
