[package]
name = "vocab"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
rss-contract.workspace = true
rss-request-context.workspace = true
thiserror = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
trybuild = { workspace = true }
serde_json = { workspace = true }

[lints]
workspace = true
